### ISSUE TITLE
Write section on ensuring diverse research participants

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/ux-guide#126]
**Background**
In a discussion at UX huddle re: what a DE&I lead in the design chapter might be responsible for. The need for guidance on ensuring diverse research participants came up. The UX guide could and should be a place folks can go for this kind of guidance.

**Acceptance criteria**
- [x] SME reviews content

**Tasks**
- [x] add content to the page 
- [x] review content

**Definition of done**
- [ ] Content describing how and why to ensure diverse research participants is added to recruitment section on the UX guide

**Comment by MelissaBraxton** [comment]
Helpful ref:

https://www.gov.uk/service-manual/user-research/find-user-research-participants#recruiting-participants-with-disabilities

**Comment by MelissaBraxton** [comment]
Scratchpad is [here](https://docs.google.com/document/d/1qxDQhPfCVuNEhSnP9xUc0kMEEkM-OC28Us2RlQp0h8Y/edit)

need to make sure we reflect new change that we can now pay incentives.

**Comment by bpdesigns** [comment]
Here is the [draft](https://docs.google.com/document/d/1qxDQhPfCVuNEhSnP9xUc0kMEEkM-OC28Us2RlQp0h8Y/edit#) in progress on this issue

**Comment by bpdesigns** [comment]
I moved this content into sections of the guide that already exist to see if we could have this content just be part of the overall guide [https://docs.google.com/document/d/1Z6CWkmLRwDA_6L2h4EE7tUrFL5M39CalC86UG06OBqg/edit?usp=sharing](https://www.google.com/url?q=https://docs.google.com/document/d/1Z6CWkmLRwDA_6L2h4EE7tUrFL5M39CalC86UG06OBqg/edit?usp%3Dsharing&sa=D&source=docs&ust=1670441426266074&usg=AOvVaw3TJb82Qa97i4jCfsGA05D8)
Show less

**Comment by MelissaBraxton** [comment]
I left a review!  In general, I think we could go deeper here. E.g., one topic that we don't cover but that I had in my mind as something to include is about partnering w/ community organizations to connect with historically marginalized groups or how we can do better at recruiting nonnative english speakers and when we might need to. We can be aspirational!

**Comment by bpdesigns** [comment]
see issue #308 Update recruitment and compensation sections and #309 add content to Debrief section

**Comment by bpdesigns** [comment]
@MelissaBraxton FYI - I created [Recruiting with communities and nonnative English speakers#320](https://github.com/18F/ux-guide/issues/320) to address your comment.
