### ISSUE TITLE
Search guidance

### ISSUE THREAD

**Issue by cmajel** [18F/ux-guide#159]
**Background**
Follow up from chat with @MelissaBraxton last week. GSA is asking that new sites include a search box and function to comply with the 21st Century IDEA Act.  

Not required for launch.

* [USWDS search component here](https://designsystem.digital.gov/components/search/)
* You can see a demo of how search can be integrated into the header in the [USWDS landing page template](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/release-2.6.0/components/preview/layout--landing.html)

**Acceptance criteria** 
- [x] Search component matches new USWDS template styling
- [x] Search component returns relevant search results

**Tasks**
- [x] Implement USWDS search component 
- [x] Confirm search.gov access and/or sign up for search.gov or 
- [x] Once front end component is in place, connect with John Jediny for help wiring up the search functionality. 
- [x] Review index/test functionality

**Definition of done**
- [ ]  One of the POs has approved the change
- [ ]  Outreach approval (if needed)

**Comment by MelissaBraxton** [comment]
Assigned both of you, @nickttng and @igorkorenfeld, per Nick's note in the channel, but feel free to chat amongst yourselves re: who wants to pick this up!

**Comment by MelissaBraxton** [comment]
@nickttng I'm going to un assign you here. We learned from Dahianna that we can get help from the coding it forward fellow who is working on this for the TTS site. @igorkorenfeld - keeping you on this since you are assisting with that effort and we may still need to implement the front end component before getting help from the fellow.

**Comment by nickttng** [comment]
@MelissaBraxton ✔️  Thx. If the CIF fellow has questions, let us know.
