### ISSUE TITLE
Re-patch side nav / content width inconsistencies

### ISSUE THREAD

**Issue by nickttng** [18F/ux-guide#161]
**Background**
Initially, the PR #157 was merged to fix side nav / content width inconsistencies; however, the merged PR #160 re-introduced the issues again. Examples: [Values and principles](https://federalist-48b3228b-0241-4802-9442-e08ff5c3e680.app.cloud.gov/site/18f/ux-guide/our-approach/values-and-principles/), [Do](https://federalist-48b3228b-0241-4802-9442-e08ff5c3e680.app.cloud.gov/site/18f/ux-guide/research/do/), etc.

**Acceptance criteria** 
- [ ] Side nav is fixed throughout the site 
- [ ] Content width is set throughout the site

**Tasks**
- [ ] Pull custom CSS from PR #157 into the latest merged by #160 
- [ ] Test throughly for accessibility, e.g. proper headings
- [ ] Test content width by trying to break it in mobile, tablet and desktop

**Definition of done**
- [ ]  One of the POs has approved the change
