### ISSUE TITLE
As a user, I want a landing page that clearly communicates what the UX guide is and how I can use it so that I know whether and how it will help me before I click further.

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/ux-guide#165]
**Background**
Need to revise landing page in accordance with [guidance from the USWDS team](https://designsystem.digital.gov/page-templates/). 

**Acceptance criteria** 
- [ ] Landing page clearly explains what the guide is and how it can be used

**Tasks**
- [X] Mock new landing page and architecture
- [X] Review mocks with team
- [ ] Implement mocks

**Definition of done**
- [ ]  One of the POs has approved the change
- [ ]  Outreach approval (if needed)

**Comment by MelissaBraxton** [comment]
Thanks for picking this up, @nickttng!  

The mocks are [here](https://app.mural.co/invitation/mural/gsa6/1587140697046?sender=qituwraanderson9105&key=5f7422d5-b5ac-4d09-bff4-c9075802d3b9)

Also, as you're going through and seeing what level of customization to the USWDs is needed, would love any recommendations you may have on how to make the site more easily editable/reducing the amount of customization needed going forward.
