### ISSUE TITLE
As a user, I need to know which top-level section the sub section I am viewing is a part of so that I don't become lost. 

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/ux-guide#166]
**Background**
Currently, when a subsection is selected, the top level section link shows inactive. This is disorienting and not consistent with the intended guide style [here](https://federalist-proxy.app.cloud.gov/site/18f/federalist-uswds-jekyll/document-with-sidenav/).

**Acceptance criteria** 
- [ ] Link styling maintains active state for top-level section when a subsection is selected. 

**Tasks**
- [x] Update main section link functionality

**Definition of done**
- [ ]  One of the POs has approved the change
- [ ]  Outreach approval (if needed)

**Comment by MelissaBraxton** [comment]
@nickttng - thanks for volunteering to pick this up! Feel free to reach out with Qs.

**Comment by jstrothman** [comment]
Closing--this is working now
