### ISSUE TITLE
Create an indicator to signal that the link isn't accessible to the general public

### ISSUE THREAD

**Issue by nickttng** [18F/ux-guide#170]
**Background**
When UX Guide goes public, it might be helpful to have an indicator which links are locked (viewable only to 18F/TTS/GSA) vs. links that can be viewed publicly. For example, TTS Slack channels are often linked, and people outside might be frustrated that the links have led them to blocked access.

**Potential indicator** 
- Use 🔒 emoji, i.e. 🔒`#g-diversity` OR suggest a better indicator 

**Acceptance criteria** 
- [ ] 🔒appears to the right of links that are only available to GSA, e.g. Google Drive links. 
- [ ] In some contexts, "GSA only" wording has been retained 

**Tasks**
- [x] Install [private-eye.js](https://github.com/18F/private-eye)

**Definition of done**
- [ ]  One of the POs has approved the change
- [ ]  Outreach approval (if needed)

**Comment by jstrothman** [comment]
Asked @MelissaBraxton in Slack whether the 18F private-eye script is the approach the team would like to take so I can update the acceptance criteria and create a pull request (or pull the script).

**Comment by jstrothman** [comment]
@nickttng I just noticed that the private-eye repo is archived. Is it still acceptable to use the script?

**Comment by nickttng** [comment]
@jstrothman I have no idea. I'll search for an answer in Slack, and if it doesn't bring it up, we'll ask in `#dev` channel, which I'll CC you.
