### ISSUE TITLE
Add analytics to the site

### ISSUE THREAD

**Issue by jstrothman** [18F/ux-guide#175]
**Background**
We'd not only like to be able to assess site usage through analytics, but it is also required: https://digital.gov/resources/checklist-of-requirements-for-federal-digital-services/

https://content-guide.18f.gov/ has DAP and GA installed but 18F.gov does not appear in the list of domains under GSA: https://pulse.cio.gov/analytics/domains/#q=General%20Services%20Administration

**Acceptance criteria** 
- [ ] Tag is confirmed to be firing in the Tag Assistant Chrome extension: Should show UA-48605964-19 (18F GA) and UA-33523145-1 (DAP GA)

**Tasks**
- [x] Set up GA & DAP 

**Definition of done**
- [ ]  One of the POs has approved the change

**Comment by jstrothman** [comment]
Pulse.CIO.gov only lists top-level domains, and the number of domains per agency. 
18F doesn't appear b/c it's a sub-domain: 18F.gsa.gov

**Comment by jstrothman** [comment]
As this is a USWDS Jekyll site, config.yml takes settings:
```
# Google Analytics & DAP tracking codes
google_analytics_ua: UA-48605964-19
dap_agency: GSA
```

The 18F Google Analytics account has a property called "Microsistes (Pages)" where we have tracking set up for 18F sites. Microsites has the property ID: UA-48605964-19, and a request can be posted to #analytics for a new view (e.g. which will filter visits to a particular hostname, such as ux-guide.18f.gov ).

Tim Lowden set up the view "UX Guide," and I have edit access to the view. We can request additional users in #analytics. 

For access to DAP data, we send an access request email per https://digital.gov/guides/dap/gaining-access-to-dap-data/ 
I will do that once the PR is merged/deployed. It is not necessary for starting to track usage.
