### ISSUE TITLE
QA review for broken links, etc

### ISSUE THREAD

**Issue by jstrothman** [18F/ux-guide#177]
**Background**
This issue is to review the site for broken links.

**Acceptance criteria** 
- [ ] TBD by PO

**Tasks**
- [ ] Review all site content, links

**Definition of done**
- [ ]  One of the POs has approved the changes
- [ ]  Outreach approval (if needed)

**Comment by jstrothman** [comment]
@MelissaBraxton I created a QA Goog doc with questions for your review: https://docs.google.com/document/d/13BvyYryKbnY2IFM9piJAJBpVU5jd4W0BYK0binn4njM/edit#heading=h.niv5q5bldkor

**Comment by MelissaBraxton** [comment]
Thank @jstrothman ! A bit of history on the plain language review - the site content has been through many many reviews and what we have in there now is the version that has been approved by our 18F Design Director (bringing the plain language and content perspective) as well as TTS Outreach, OGC, OSC and others. I've edited the issue to focus on broken links.

**Comment by jstrothman** [comment]
@MelissaBraxton Understood--I was sparing in plain lang changes, knowing that review had happened. Most cases were to break long sentences into two shorter sentences. There's one that had significant complexity along w/two idioms--I mentioned it and suggested change in the [UX Guide QA Review Questions doc](https://docs.google.com/document/d/13BvyYryKbnY2IFM9piJAJBpVU5jd4W0BYK0binn4njM/edit#heading=h.niv5q5bldkor) rather than going ahead and changing.

For the changes I did make, the following options would all be fairly quick for me. Would you prefer:
1. Revert them as the necessary review has already been done
2. Leave them and call them out specifically in the pull request
3. Leave them and no need to call them out b/c they're visible by reviewing the commits

**Comment by jstrothman** [comment]
@nickttng There's a broken layout in this branch that I'd appreciate if you could look at before I do a PR. (Or tell me if that should happen as part of the PR review.) 

- Branch: jstrothman-qa-review
- [Commit where I noticed it](https://github.com/18F/ux-guide/commit/4dd79cc96a6329576530cd90161b8a8592b513bf)

Our Approach > Stay Lean: At full screen width, content appears below nav instead of in two columns
![uxguide-lean-borked-layout](https://user-images.githubusercontent.com/1080991/81819047-d0902b00-94fc-11ea-83f1-f0a09f083476.png)

**Comment by nickttng** [comment]
@jstrothman The `blockquote` element was creating the breakage, so I've set the `max-width` property value for it in this [commit](https://github.com/18F/ux-guide/commit/59fc67b690ef3bb11327aa538610affc8ca89df4) in your branch. Let me know if this patch doesn't completely address the issue.

**Comment by jstrothman** [comment]
@nickttng Looks great--thank you!
