### ISSUE TITLE
Small screens: Secondary navigation is at page-bottom

### ISSUE THREAD

**Issue by jstrothman** [18F/ux-guide#178]
**Background**
When browsing the site on small screens, the side navigation appears at the bottom of the page. Some of the UX Guide pages are quite long. (See screenshot at bottom of this description.) Moving the secondary navigation to the top of the page, visitors will be able to:
* Recognize what all is covered in the page and in the section
* Navigate to another section without having to scroll all the way down

The demo site shows the sub-navigation at the page top on small screens: https://federalist-ce810add-9092-4627-8246-9b65cf94623c.app.cloud.gov/site/18f/federalist-uswds-jekyll/document-with-sidenav/ 
On small screens, the secondary nav also takes up the full width of the screen in the demo, but in the UX Guide it is auto width. This doesn't affect usability, but looks odd to me.

**Enhancements**
In addition to the fix of moving the navigation for small screens:
* Make subnav take up full width of screen on small screens
* Add a link: 'Back to top' at the bottom right of all pages, all screen sizes, since the stick nav does not actually stick and follow you down the page

**Acceptance criteria** 
- [ ] On screen sizes where navigation is collapsed, show the secondary/tertiary nav at page top instead of page bottom 
- [ ] On screen sizes where nav is collapsed, make secondary/tertiary nav visually take up full width of screen as on https://federalist-ce810add-9092-4627-8246-9b65cf94623c.app.cloud.gov/site/18f/federalist-uswds-jekyll/document-with-sidenav/ 
- [ ] Add a 'Back to top' link at the page bottom (all screen sizes) that links to #main-content

**Tasks**
- [ ] 
- [ ] 

**Definition of done**
- [ ]  One of the POs has approved the change
- [ ]  Outreach approval (if needed)

Screenshot of full page at small size with sub-navigation at page bottom:
![ux-guide 18f gov_research_privacy_](https://user-images.githubusercontent.com/1080991/81594102-648fb480-938e-11ea-8903-0eb0dbb9ce69.png)

**Comment by jstrothman** [comment]
Taking this issue back as @MelissaBraxton requested these adjustments in https://github.com/18F/ux-guide/pull/173

**Comment by jstrothman** [comment]
Retaining issue, even though it's a dupe, for checklist/review purposes when #173 is complete

**Comment by jstrothman** [comment]
Actually, this issue is fully covered in #173 and #182
