### ISSUE TITLE
Required Web Content and Links

### ISSUE THREAD

**Issue by jstrothman** [18F/ux-guide#179]
**Background**
The [New Site or Redesign Checklist for Teams](https://docs.google.com/spreadsheets/d/1k1egCYfKc12v0ruFtI5ToNGCtB2iCmYjyHrvUnPzCvY/edit#gid=0) includes [Required Web Content and Links](https://digital.gov/resources/required-web-content-and-links/)

**Acceptance criteria** 
- [x] Secondary agency sites need an “About” page that describes your site and links to your own website policies. It should also link to the primary agency’s “About” page. (18F.gsa.gov has a primary nav link to its About page; the footer includes links to Policies and Standards)
- [x] Federal agencies must: develop an accessibility statement, add it as an “Accessibility” page on the agency’s main website and provide a link to it, link to it on all secondary public-facing websites. (Not needed for launch - link to GSA accessibility statement is included in footer template, #158 )
- [ ] Agencies must clearly identify external links from their websites. (can wait until after launch--there should be few of these since we aimed to link to mostly gov resources per OGC guidance)
- [x] A link to a page on 18F main site that includes [certain content as required by the FOIA](https://www.justice.gov/oip/blog/foia-update-oip-guidance-electronic-foia-amendments-implementation-guidance-outline) that includes information about how the public can request information under the Freedom of Information Act (FOIA). (Not needed for launch - link  is included in footer template)
- [x] Link to [USA.gov](https://www.usa.gov/) and to [USAGov en Español](https://www.usa.gov/espanol/) (Not needed for launch - link  is included in footer template)
- [x] All federal public websites must post privacy policies on each website, including instructions on how to “[opt-out](https://www.usa.gov/optout-instructions)” of any web tracking and measurement technologies the agency may use; (Not needed for launch)

**Tasks**
- [x] Add link from Footer (or About page) to 18F accessibility guide
- [ ] Review UX Guide site for external links that will be retained and add icon & text to indicate it is a non-gov link
- [ ] Review 18F Methods site for external links that will be retained and add icon & text to indicate it is a non-gov link
- [x] Find out what the FOIA info requirements (unclear from reading page linked above). Would need to be added to 18F.gsa.gov and then have a link added to the UX Guide
- [x] "Have a question about government services? Contact [USA.gov](https://www.usa.gov/) or [USAGov en Español](https://www.usa.gov/espanol/)"
- [x] Decide how to tackle privacy policy requirement (e.g. put one on 18F site and link to it?)

**Definition of done**
- [ ]  One of the POs has approved the change
- [ ]  Outreach approval (if needed)

**Comment by jstrothman** [comment]
Retaining issue, even though it's a dupe, for checklist purposes when #174 is complete

**Comment by jstrothman** [comment]
@bpdesigns Should we use the `launch` icon from the [USWDS icons](https://designsystem.digital.gov/components/icon/) for external links?

Based on a [search for 'external link' on the Noun Project](https://thenounproject.com/search/icons/?iconspage=1&q=external%20link), it seems like pretty common usage.

**Comment by bpdesigns** [comment]
@jstrothman yes that makes sense based on your note and the above acceptance criteria.

**Comment by mgwalker** [comment]
How are external links identified? Do content authors need to mark them up themselves, or is there/should there be some kind of automation to find them? (e.g., anything that does not go to a `.gov` automatically gets the launch icon)

**Comment by bpdesigns** [comment]
The [About page](https://github.com/18F/ux-guide/blob/main/_pages/about.md) has links to github and creative commons.
The resources page has external .gov links under **Additional reading** 

The other links in the site that I'm aware of are  
- links referring to different pages within the guide (using baseurl)
- links with a .gov @mgwalker some of them go to other federal and state sites so that could miss external sites.  
- links that go to internal google docs 

@jstrothman can you confirm which of the following this issue is about?
1. labeling all sites external to the UX Guide 
2. labeling sites that not .gov

**Comment by MelissaBraxton** [comment]
Closing bc/ we created #297 w/ remaining work that needs to be done here.
