### ISSUE TITLE
Remove "(GSA only)" text from locked links

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/ux-guide#180]
**Background**
Now that we've enhanced the site's accessibility with lock links, we can remove the GSA only text. 

**Acceptance criteria** 
- [ ] We no longer have redundant "GSA only" text on locked links

**Tasks**
- [x] Remove "(GSA only)" text from all links where it appears

**Definition of done**
- [ ]  One of the POs has approved the change
- [ ]  Outreach approval (if needed)
