### ISSUE TITLE
As a user, I need the side nav to appear at the top of the section so that I don't become lost

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/ux-guide#182]
**Background**
When browsing the site on small screens, the side navigation appears at the bottom of the page. Some of the UX Guide pages are quite long. (See screenshot at bottom of this description.) Moving the secondary navigation to the top of the page, visitors will be able to:
* Recognize what all is covered in the page and in the section
* Navigate to another section without having to scroll all the way down

The demo site shows the sub-navigation at the page top on small screens: https://federalist-ce810add-9092-4627-8246-9b65cf94623c.app.cloud.gov/site/18f/federalist-uswds-jekyll/document-with-sidenav/ 
On small screens, the secondary nav also takes up the full width of the screen in the demo, but in the UX Guide it is auto width. This doesn't affect usability, but looks odd to me.

**Enhancements**
In addition to the fix of moving the navigation for small screens:
* Make subnav take up full width of screen on small screens

**Acceptance criteria** 
- [x] on smaller screens, side navigation appears at the top of the section.

**Tasks**
- [x] On screen sizes where navigation is collapsed, show the secondary/tertiary nav at page top instead of page bottom 
- [x] On screen sizes where nav is collapsed, make secondary/tertiary nav visually take up full width of screen as on https://federalist-ce810add-9092-4627-8246-9b65cf94623c.app.cloud.gov/site/18f/federalist-uswds-jekyll/document-with-sidenav/ 

**Definition of done**
- [ ]  One of the POs has approved the change
- [ ]  Outreach approval (if needed)

Screenshot of full page at small size with sub-navigation at page bottom:
![ux-guide 18f gov_research_privacy_](https://user-images.githubusercontent.com/1080991/81594102-648fb480-938e-11ea-8903-0eb0dbb9ce69.png)

**Comment by MelissaBraxton** [comment]
Per your request @nickttng, creating this as a new issue to separate it from #173. :hat-tip: to @jstrothman for articulating much of this in an earlier iteration.
