### ISSUE TITLE
Accessibility fix - skipnav link takes folks to the top of the nav, rather than to the main content 

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/ux-guide#183]
**Background**
Per USWDS guidelines and for overall accessibility, we need to give folks using screen readers a way to skip the navigation and get to the main content. While we have a skipnav link, it currently takes people to the top of the nav and doesn't actually let them skip it. 

**Acceptance criteria** 
- [x] Skipnav to #main-content link bypasses nav and takes users to the main content

**Tasks**
- [x] Move #main-content links to the beginning of the main content
- [x] Use a screen reader to manually test the skipnav link to confirm that it takes folks to the right place

**Definition of done**
- [ ]  One of the POs has approved the change
- [ ]  Outreach approval (if needed)

**Comment by igorkorenfeld** [comment]
The update to the latest uswds-jekyll theme seems to have resolved this issue for us. I tested it with VoiceOver on the top level pages and it seemed to take me to the right area. I believe we could close this issue without any further changes, if it looks good to @MelissaBraxton and/or @anatecture
