### ISSUE TITLE
Copy edits for future consideration

### ISSUE THREAD

**Issue by jstrothman** [18F/ux-guide#190]
**Background**
There are some copy edits that could improve plain language usage in the UX Guide

**Acceptance criteria** 
- [x] Copy edits look correct 

**Tasks**
- [x] Review [commit that reverted some copy changes](https://github.com/18F/ux-guide/commit/321e157dcb594a7be3413f9a84162585d0717e0f) for purposes of initial release
- [x] Make any changes, as appropriate

**Definition of done**
- [ ]  One of the POs has approved the change
- [ ]  Outreach approval (if needed)

**Comment by jstrothman** [comment]
Additional paragraph that could use edits to replace idioms and reduce sentence complexity. (Also to make explicit why the “need to appreciate” one type of benefit before the other:

Our Approach > Meet our partners where they are > [Design maturity](https://ux-guide.18f.gov/our-approach/meet-partners-where-they-are/#design-maturity)

**Current paragraph**: “People who are new to design will need to appreciate its direct benefits (like improved usability and customer adoption) before its indirect benefits (such as helping the team identify the most important problems for them to solve). We aim to give our partners something tangible, and let them experience the show before pulling back the curtain.”

**Suggested edit**: For people who are new to design, it is easier to adopt strategies that do not require change in individual or team participation and that are easily measured, such as strategies that result in improved usability and customer adoption. Once people observe evidence-based successes, we can bring them further into the design process.

**Comment by aditirao** [comment]
I believe I've reverted all the changes, and made the edit included in the comment above. They're all separate pull requests because I couldn't figure out how to put them all in one pull request. Please let me know if there are any questions!
