### ISSUE TITLE
Research What is It repeats research landing page

### ISSUE THREAD

**Issue by jstrothman** [18F/ux-guide#191]
**Background**
Clarify the basics’ section ‘What is it’ repeats the text from the Research landing page. (The only difference being that Clarify the basics adds a link to Defining Design on the text: ‘Design involves continuous decision making.’)

**Acceptance criteria** 
- [x] New content on one of the pages looks good
- [x] Content is no longer repeated 

**Tasks**
- [x] Decide which page should get new content
- [x] Draft new content
- [x] Replace the content selected for replacement

**Definition of done**
- [x]  One of the POs has approved the change
- [ ]  Outreach approval (if needed)

**Comment by lauraponce** [comment]
I spent some time thinking through this and feel like it makes the most sense to keep the content in Clarify the basics > What it is and update the `Research` landing page with new content. My reasoning for this is that the other landing pages for `Our approach` and `Design` are ~1 paragraph blurbs about what to expect in the following section, and this content doesn't match that pattern.

I think the `What it is` content fits in well with the flow of that page and tees up the content below it. It doesn't seem to fit in as well on the `Research` landing page because it's speaking at more of a higher level and doesn't say what to expect in the section like the `Our approach` and `Design` pages do.

Here's a proposal for what we could use on the `Research` landing page in place of the duplicative content:

### Draft: 
> The Research section is the foundation of the UX Guide and is core to our work at 18F. This section covers everything you need to know about conducting ethical, inclusive, and unbiased user research from start to finish and includes information about privacy and storing PII as well as legal considerations such as PRA and compensation. 

__________

For reference, here's what we say on the `Design` landing page:

>This section covers prototypes, how they inform our work and what prototypes help us convey. It contains resources to get started prototyping with our website publishing platform, Federalist, as well as information and resources related to the U.S. Web Design System, —the set of website standards agencies should use per the 21st Century IDEA.

and on the `Our approach` landing page:

>Our Approach describes essential aspects that shape our design practice: our team values and principles, our definitions of design, and our commitment to staying lean. It describes how we meet partners where they are.

Thoughts on this, @jstrothman?

**Comment by christophermather** [comment]
Marked as "Done" on 2/14/2023. Marking "Closed" now.
