### ISSUE TITLE
Update incentives and compensation content

### ISSUE THREAD

**Issue by jstrothman** [18F/ux-guide#192]
**Background**
Now that we have approval to compensate research participants, some of the UX Guide content needs updating:

Research: Do > [Incentives](https://ux-guide.18f.gov/research/do/#incentives) section suggested edit:
***Participant Compensation***
“Previously, 18F did not have the legal authority to offer compensation to research participants; see Legal for more information. In cases where you can’t pay people, think creatively about how you might appeal to potential research participants in lieu of a monetary incentive. For instance, you might consider framing their participation as an opportunity to see something in development, or to read about the research findings before it’s shared with a wider audience (if possible). We often appeal to people’s desire to contribute to the common good by helping to improve government services.”

Research > [Legal](https://ux-guide.18f.gov/research/legal/)
Needs review for changes re incentives

**Acceptance criteria** 
- [ ] 18F staff users can find the information they need to get started if they want to offer incentives and/or compensate research participants. 

**Tasks**
- [x] Draft edits
- [x] Make edits
- [x] Submit PR

**Definition of done**
- [x]  One of the POs has approved the change
- [ ]  Outreach approval (if needed)
