### ISSUE TITLE
Design landing page needs content

### ISSUE THREAD

**Issue by jstrothman** [18F/ux-guide#193]
**Background**
Currently, the [Design section landing page](https://ux-guide.18f.gov/design/) is empty. It may be intended to have content from [this folder](https://drive.google.com/drive/folders/1npBvmkYo3pbGAElL1gplEH9Lp_hLPXNw), such as the [Overview doc](https://docs.google.com/document/d/1kkUfW-7elsyxSSwqmGkG8JBgzsgRp_zs9a-QmP2j0Os/edit#heading=h.wt5e1yo4anbe) content.

**Acceptance criteria** 
- [ ] Design landing page content is approved and looks correct in the site

**Tasks**
- [ ] Draft Design landing page content 

**Definition of done**
- [ ]  One of the POs has approved the change
- [ ]  Outreach approval (if needed)

**Comment by qmanderson1** [comment]
Design summary content added.
