### ISSUE TITLE
Replace writing and design labs with microrequests info

### ISSUE THREAD

**Issue by jstrothman** [18F/ux-guide#194]
**Background**
Now that the writing and design labs have been replaced by microrequests, we need to update the related content:
* Overview > Resources > [Labs](https://ux-guide.18f.gov/resources/#labs)
* Research > Make research actionable > [Presenting the work](https://ux-guide.18f.gov/research/make-research-actionable/#presenting-the-work)

**Acceptance criteria** 
- [x] Users can find and navigate to info on how they can get short term help by submitting a microrequest from the UX guide

**Tasks**
- [x] Draft microrequests language
- [x] Submit PR

**Definition of done**
- [x]  One of the POs has approved the change
- [ ]  Outreach approval (if needed)

**Comment by qmanderson1** [comment]
[I've added my suggested edits to this document.](https://docs.google.com/document/d/119k1BpT65azOCWWyTTbtNogp2aWCLtxRp8FU7vNQ9K8/edit#heading=h.wd5b66ev030o)
Would someone take a look and review it before I put the changes in the repo? Thanks!

**Comment by aditirao** [comment]
I've made changes to the Resources page based on Qituwra's suggestion. I made a mistake and didn't create a PR but instead committed the changes directly to the master branch, viewable here: https://github.com/18F/ux-guide/commit/47db7aab56e195046a87a9c4c18c0d11a6cf446f.

**Comment by aditirao** [comment]
I've also made changes to Research > Make research actionable > [Presenting the work](https://ux-guide.18f.gov/research/make-research-actionable/#presenting-the-work) also based on Qituwra's suggested edits; and made pull request #227 for those changes. @jstrothman I've requested your review of the changes. Thanks!
