### ISSUE TITLE
Implement sticky footer on all viewports

### ISSUE THREAD

**Issue by nickttng** [18F/ux-guide#212]
**Background**
Find a better, permanent solution for #211 

**Acceptance criteria** 
- [ ] Sticky footer is enabled on both mobile and tablet without recreating the mobile menu issue 

**Tasks**
- [ ] Research a better solution via teh interwebz and/or ask around in TTS

**Definition of done**
- [ ]  One of the POs has approved the change

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.

**Comment by MelissaBraxton** [comment]
There may be an opportunity to merge this with #211.

**Comment by bpdesigns** [comment]
Closing this issue. Its unclear why there was an ask for a sticky footer. Team agrees this is not something we think should be there
