### ISSUE TITLE
Update meta description

### ISSUE THREAD

**Issue by jstrothman** [18F/ux-guide#223]
**Background**
The current meta description that appears when people link in Slack and on social to any UX Guide page: "This is the beginning of a guide that will house resources, norms, and practices for doing user experience research and design work at 18F."

**Acceptance criteria** 
- [ ] There are page-specific meta descriptions for all pages of the Guide

**tasks**
 - [ ] Write meta description content for all pages
 - [ ] Implement meta description content
    - this is currently handled in the Jekyll `_config.yml` file, incorporated via the USWDS layout template

**Definition of done**
- [ ]  One of the POs has approved the change

**Comment by jstrothman** [comment]
I wonder if the Guides team has any suggestions / guidance re themes to cover in the meta description (and possibly for updating the initial paragraph on the landing page, which is very 18F-audience focused).

**Comment by bpdesigns** [comment]
@annepetersen any suggestions for guide meta descriptions?

**Comment by bpdesigns** [comment]
This [spreadsheet](https://docs.google.com/spreadsheets/d/1WJIDIMJK2Zzk8bA8DOmqd6Fbfp-tHSbk0-Cv9WPfNlo/edit#gid=0) is a good place to start with content for meta descriptions. It links to the original guide pages which include goals for each page

**Comment by mgwalker** [comment]
I need to correct (or clarify?) myself from yesterday's conversation.

I said we could update a value in the guide config file and be done. That is only true if it's okay for every page in the guide to have the same meta description. If each page should have its own unique meta description, then they will all need to be updated to include a `description` key in the frontmatter. It's more engineering work than I said yesterday, though provided the content, it should still be pretty low. Hours instead of minutes, maybe?

**Comment by bpdesigns** [comment]
Thanks for checking on the LOE on this issue @mgwalker.

Each page should have a unique meta description. @echappen let me know if you'd like to cowork on the content. I'm happy to do so.
