### ISSUE TITLE
Updating research plan helpers

### ISSUE THREAD

**Issue by cmajel** [18F/ux-guide#243]
**Background**
I've noticed that the public [markdown research plan template](https://github.com/18F/ux-guide/blob/master/_pages/resources/research-plan.md) doesn't have the same helper text as the [google doc research plan template](https://docs.google.com/document/d/1M3GP1JWW9mlZAAONklogurd8qXZLLgBqcKfU5HiS9h0/edit#heading=h.6yl3ejuygtuw) 🔒 for 18F team use. Looking at the history it appears that the markdown research plan template is more current, and some helpers were removed. 

Some of the links (both in markdown and in google docs) can also now be updated to new public UX Guide links.

I personally have found the helpers useful when I am writing research plans and communicating the goals of each point to partners and other designers: it helps get us on the same page of what the section should accomplish. 

Some open questions:
* What are the right helpers to use for each section?
* Should public markdown version and the google doc version for 18F team use be the same?

**Acceptance criteria** 
- [x] Research plan templates provide consistent guidance across mediums

**Tasks**
- [ ] Answer open questions
- [x] Update section helpers in both templates
- [x] Update links in both templates

**Definition of done**
- [x]  One of the POs has approved the change
- [ ]  Outreach approval (if needed)

**Comment by jstrothman** [comment]
I think we should strive for parity between the public markdown version and the GSA0-only google doc versions of docs in the Guide. It's valuable for them to be different in that we can include external links in our internal-facing templates, where we largely need to avoid 3rd-party links in the public-facing templates.

I updated the Google doc to use the new helper text from the markdown document, while retaining some of the helper text 3rd-party links.

**Comment by jstrothman** [comment]
Regarding "What are the right helpers to use for each section?" we provide for each element of the research plan:
* Reason why the element is useful
* Some guidance as to what to include
* When available, links to more information in the UX Guide or 18F Methods site.

**Comment by cmajel** [comment]
@jstrothman I like how the Google doc and markdown versions are now more aligned. This feels like a good outline for what we should include in helpers. 

I made one comment on the Google doc version, otherwise these changes look good to me 👍
