### ISSUE TITLE
As a visitor, I can recognize where I am in relation to the whole page

### ISSUE THREAD

**Issue by jstrothman** [18F/ux-guide#254]
**Background**
The [USDS Discovery Sprint Guide](https://sprint.usds.gov/), which also uses the Federalist template with sidenav, highlights the active sidenav section as you scroll. This would help our readers, particularly on our very long pages. 
Should we do something a bit more visible than the default darker gray/bold treatment for the active link?

**Acceptance criteria** 
- [ ] As you scroll the Research > Plan or Do page (examples of long pages), the side navigation highlights as you scroll
- [ ] On small screens, the new highlighting functionality may still work, but does not impact the links present at page top

**Tasks**
- [ ] Design treatment
- [ ] Implement

**Definition of done**
- [ ]  One of the POs has approved the change
