### ISSUE TITLE
Redirect Usability Test Quality 

### ISSUE THREAD

**Issue by jstrothman** [18F/ux-guide#259]
**Background**
A search for `usability test` includes this result: https://ux-guide.18f.gov/_pages/resources/usability-test-quality.html
which is a page that doesn't use the template. Let's redirect it to https://github.com/18F/ux-guide/blob/master/_pages/resources/usability-test-quality-heuristics.md
(see the redirect metadata on`/_pages/resources/usability-test-quality-heuristics.md`)

**Acceptance criteria** 
- [ ] Users can access formatted, usability test quality heuristics content from the GitHub page and view it on the UX Guide website
- [ ] The old page redirects to the new page / we don't break anything for folks who have the old link

**Tasks**
- [ ] 
- [ ] 

**Definition of done**
- [ ]  One of the POs has approved the change
