### ISSUE TITLE
Add descriptive research to section on research types

### ISSUE THREAD

**Issue by jstrothman** [18F/ux-guide#276]
The [Research types section](https://ux-guide.18f.gov/research/clarify-the-basics/#research-types) includes foundational, generative, and evaluative, but doesn't have descriptive research.

Let's add something like:
**Descriptive**
The observation and description of what you’re studying. Descriptive research is what you do when you already have a problem and need to understand the context entirely.
(The above is taken from @boonerang training day 1. Will link, once it's shared)

**Acceptance criteria**
- [ ] Content on descriptive research is live

**tasks**
 - [x] Draft revision in a doc
 - [x] Pair on implementing
 - [ ] PO reviews

**Comment by claireb-gsa** [comment]
[Working on draft content in a google doc](https://docs.google.com/document/d/1nARPrsQVS9-_Uda2vACpWm619kJqMWm-Gk1Wz5VLiQg/edit#)

**Comment by claireb-gsa** [comment]
draft is complete - requested partnering/review in slack channel before implementing the changes.
