### ISSUE TITLE
Review guidance on Trauma informed research practices Part 1

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/ux-guide#291]
**Background**
There is no guidance on Trauma informed research practices in the ux guide but should be. Potentially we could update the following pages: [ethical considerations](https://ux-guide.18f.gov/research/plan/#ethical-considerations), [Preparing an interview guide](https://ux-guide.18f.gov/research/do/#preparing-an-interview-guide), [getting informed consent](https://ux-guide.18f.gov/research/do/#getting-informed-consent), [moderating research sessions](https://ux-guide.18f.gov/research/do/#moderating-research-sessions) and [ethics](https://ux-guide.18f.gov/research/ethics/) 

**reference material**

- references from the [2022 Research Guild Trauma Informed workshop series](https://drive.google.com/drive/folders/1fSc6qP980OLZmP3NCVIAqkbKB4h99HAR)
- [Trauma informed research slides](https://docs.google.com/presentation/d/1UwNyS3T9HPCYgHLg9OIWmqkNh4kMQrk2okP_DZjfJiA/edit#slide=id.g5ecdbbee9e_0_0)
- SAMHSA research training slides [starting at 39](https://docs.google.com/presentation/d/17MfQiwcN9U7kvfN3KqGGtowQSSazMzJ8QZ1pwZldMXQ/edit#slide=id.g5d9ee75ee8_0_20)
- [Transforming Government Services with Empathy](https://docs.google.com/presentation/d/1r8WyjGlbbGIRj8OJrFOZGn33bQ9bHwOvs0aJz0PP6aA/edit#slide=id.g96c90728c6_0_2415)
- [18F Team Coffee 10/7 - DOJ HC Prevention - slide 13](https://docs.google.com/presentation/d/1fx-XBzmthnCwbDCIjGQVZNC1-yqoRbCoFAOcexVEq0c/edit#slide=id.g162ec938a6f_0_1)

**Acceptance criteria** 
- [x] guidance on trauma informed research is drafted. 

**Tasks**
- [x] review references on trauma informed practices 
- [x] draft a doc with new content
- [x] share doc in the 18 design channel research guild slack channels for comment
- [x] review from @bpdesigns or @MelissaBraxton 

### Point of contact on this issue
You can reach out to @bpdesigns 

**Billable?**

- [ ] Yes
- [x] No
If yes, tock code:

**Skills needed**

- [x] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [x] No

How much time do you anticipate this work taking?
-  two weeks
- 
**Definition of done**
- [ ]  @bpdesigns or @MelissaBraxton has approved the update

**Comment by MelissaBraxton** [comment]
From UX Huddle on 11/2. We had notes about how we could also break down or point to things we already consider best practices here, but add an explanation about WHY it's a best practice. Things like:

- Telling people about the topics we'll be discussing in advance
- Giving people advanced notice that the meeting will be recorded
- Letting people know they can take a break or end the interview at any time
- etc...

**Comment by bpdesigns** [comment]
Work with ADA, SAMHSA and DOJ could also inform this content. 

Additional references include 
- [SourceAmerica pilot learnings](https://docs.google.com/document/d/1S4kDgL80raTT1KkwI-03ZrLuBFfTtYqR4bLOSZVJYS8/edit) 
- [Recruiting participants who use assistive tech](https://docs.google.com/presentation/d/14nTo_YRmp2LjFm33GHW5zRY5iTSkfEHv91tHLo6b5Qk/edit#slide=id.g153d5c180e0_0_48)
- references from the[2022 Research Guild Trauma Informed workshop series](https://drive.google.com/drive/folders/1fSc6qP980OLZmP3NCVIAqkbKB4h99HAR)
- [Trauma informed research slides](https://docs.google.com/presentation/d/1UwNyS3T9HPCYgHLg9OIWmqkNh4kMQrk2okP_DZjfJiA/edit#slide=id.g5ecdbbee9e_0_00

**Comment by MelissaBraxton** [comment]
Noting that @juliaklindpaintner can also be a resource here having recently completed a training on this topic.

**Comment by bpdesigns** [comment]
Content that covers some of this has been added to the "Do" page under [moderating sensitive research sessions](https://ux-guide.18f.gov/research/do/#moderating-sensitive-research-sessions)

**Comment by bpdesigns** [comment]
calling this done
