### ISSUE TITLE
Follow up on 2021 recommendations to improve UX Guide usability and findability

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/ux-guide#295]
**Background**
Some analysis of analytics in FY 21 produced a set of recommendations that weren't pursued. We want to revisit and decide which to implement and how.  This is issue covers reviewing past recommendations, deciding which to pursue and in what priority order, as well as the creation of new issues to actually track the work. 

**Acceptance criteria**
We have translated the recommendations in [this deck](https://docs.google.com/presentation/d/1trsB6MLyrIEL4cbvsqMVtNujFCTQTE7OYhcj14FDag4/edit#slide=id.g78bab2de6b_0_123) into new GitHub issues
New issues are prioritized

**Tasks**

- [x]  Review [this deck](https://docs.google.com/presentation/d/1trsB6MLyrIEL4cbvsqMVtNujFCTQTE7OYhcj14FDag4/edit#slide=id.g78bab2de6b_0_123) into new GitHub issues
- [x] Articulate new user needs statements
- [x] Create draft issues for new needs statements
- [x] Review and prioritize during backlog grooming, and refine prioritized issues

**Comment by mgwalker** [comment]
Created #300 to capture the recommendation from [slide 12](https://docs.google.com/presentation/d/1trsB6MLyrIEL4cbvsqMVtNujFCTQTE7OYhcj14FDag4/edit#slide=id.g78bab2de6b_0_87): **Should we move our resources out of GitHub pages?**

My only question is whether there's a reason that content was linked to GitHub instead of being published in the guide. The doc lists several cons for being in GitHub, but presumably there were some pros that led to that happening in the first place.

**Comment by mgwalker** [comment]
That sounds like we can go ahead and pull them directly into the guides then. Hooray!

**Comment by mgwalker** [comment]
#223 also comes from the deck and addresses slides 10 and 11.

**Comment by MelissaBraxton** [comment]
Closing - We now have the following issues to follow up on these recs!
[#300](https://github.com/18F/ux-guide/issues/300) 
[#223](https://github.com/18F/ux-guide/issues/223)
[#570](https://github.com/18F/methods/issues/570)
