### ISSUE TITLE
Label external non federal links on the 18F Methods site

### ISSUE THREAD

**Issue by bpdesigns** [18F/ux-guide#297]
**Background**
Agency websites must clearly state that the content of external links to non-federal agency websites is not endorsed by the federal government and is not subject to federal information quality, privacy, security, and related guidelines.

- Any link that is not a federal .gov or .mil website is considered an external link. - - Websites that are .gov but are not Federal is considered an external 

Required by: [OMB M-17-06, Policies for Federal Agency Public Websites and Digital Services](https://www.whitehouse.gov/wp-content/uploads/legacy_drupal_files/omb/memoranda/2017/m-17-06.pdf) (PDF, 1.2 MB, 18 pages, November 2016)

Suggested icon approach: use the launch icon from the [USWDS icons](https://designsystem.digital.gov/components/icon/) for external links. Based on a [search for 'external link' on the Noun Project](https://thenounproject.com/search/icons/?iconspage=1&q=external%20link), it seems like pretty common usage.

**Acceptance criteria** 
-[ ] All links in the 18F Methods site that are not a federal .gov or .mil website are clearly indicated 

**Tasks**
- [ ]  Review 18F Methods site for external links that will be retained and add icon & text indicate non federal links

**Definition of done**
- [ ]  One of the POs has approved the change
- [ ]  Outreach approval (if needed)

**Comment by claireb-gsa** [comment]
For the record, Digital.gov's guidance is easier to parse than the OMB PDF - https://digital.gov/resources/required-web-content-and-links/#external-links

**Comment by kmori** [comment]
With this definition, would internal Google docs be considered "external" since they are not .gov or .mil?

**Comment by bpdesigns** [comment]
Great question @kmori - @MelissaBraxton do you remember how google docs were considered here?

**Comment by MelissaBraxton** [comment]
I think we can close this issue. We have #340 to cover the Gdocs styling, and all external links have already been updated.
