### ISSUE TITLE
Add guide to contributing to the README

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/ux-guide#30]
The current contributing guide is specific to original authors internal to 18F. We need to update to be geared toward public contributors who may be outside of 18F or even outside government.

**Acceptance criteria** 
- [x] We have a public facing description of our guide to contributors 
- [x] We have a clear, default issue template that is easy to use for contributors and the UX Guide product team to use

**Tasks**
- [X] Review existing "contributing guide" example
- [x] Determine needed approvals (outreach?)
- [x] Create an issue template for public users
- [x] Set template to default for new issues
- [X] Draft contributing guidance
- [x] Draft instructions for submitting new issues
- [x] Publish contributing guide on GitHub

**Definition of done**
- [x]  PO approval

**Comment by MelissaBraxton** [comment]
Examples to consider
 - USWDS 
 - 18F handbook
 - Check for acq repos
 - Method cards
 - Other guides (content guide, devops handbook, USDS guides)

**Comment by MelissaBraxton** [comment]
Draft CONTRIBUTING text is here: https://docs.google.com/document/d/1TLw8_hvJc1BoGFPHUjjtRddy_B4YlZrFUBch5KbWB9g/edit?usp=sharing

**Comment by MelissaBraxton** [comment]
I have a Q out to Dahianna re: needed approvals, but since the repo is currently private I'm going to go ahead and add the content.
