### ISSUE TITLE
Update Ethics page

### ISSUE THREAD

**Issue by bpdesigns** [18F/ux-guide#312]
**Background**
We should review our Ethics guide page. Here are a few things I see missing, there are likely others: 
- Consider who benefits, who decides, who’s missing, who might be harmed by your research 
- Understand the history of the group and challenges before engaging with them to understand the basic context. Design and technology are never neutral. We have the system created and can be optimized to be more inclusive or less inclusive. 
- Don’t remove data from its context. Decontextualized and recontextualised data doesn’t not honor the people you are talking to.
- Avoid doing research as an extractive process. Extractive relationship pull data from people

**Acceptance criteria** 
- [ ] Readers of the Ethics page will understand how 18F team members Ethics inform their work  

**Tasks**
- [ ] Review Ethics page for updates and additional content 
- [ ] Create a word doc to show proposed changes from review
- [ ] Get input from design and research teams, either in huddles, crit or guild meetings.
- [ ] Refine updates in word doc and share out in slack for design and research team input
- [ ] Update the page in github

**Definition of done**
- [ ]  One of the POs has approved the change
- [ ]  Outreach approval (if needed)

**Comment by bpdesigns** [comment]
@austinhernandez FYI

**Comment by MelissaBraxton** [comment]
@egamble23  - Can help out with content editing and plain language review

**Comment by austinhernandez** [comment]
@MelissaBraxton i asked for feedback for this ethics content but not getting any individual volunteers. i asked the product design team for time tomorrow, but in order to speed this along i wanted to tag someone to give input from the ux design / research team

**Comment by MelissaBraxton** [comment]
@bpdesigns - Given that the process of soliciting and incorporating feedback from a broader group of stakeholders is likely a multi--increment process, I'm thinking we should down-scope TLC crew's involvement on this issue to writing the initial draft that you can then shop around for input and refine. If you're on board with that, then I believe we can call this "done" from our standpoint. How does that sound?
