### ISSUE TITLE
Making content consistent in the ux guide 

### ISSUE THREAD

**Issue by bpdesigns** [18F/ux-guide#313]
**Background**
See this [thread](https://gsa-tts.slack.com/archives/C03LHEFGSF7/p1671139450856569) from Anne on content considerations.
 
**Acceptance criteria** 
- [ ] Contributors to the UX Guide understand what tone and voice they should write content from so readers understand who is the focus of the content
- [ ] Contributors have clarity on definition of common terms so  readers of the guide have clarity about what is being discussed 

**Tasks**
- [ ] 
- [ ] 

**Definition of done**
- [ ]  One of the POs has approved the change
- [ ]  Outreach approval (if needed)
