### ISSUE TITLE
Review the UX Guide and Method cards for how we work now 

### ISSUE THREAD

**Issue by bpdesigns** [18F/ux-guide#314]
**Background**
The 18F team has evolved our design research practices and deepened our work addressing DEIA. Its time to reflect as a group how we practice now and what standards we want to hold ourselves to as we work to deliver more equitably for the public. 

**Acceptance criteria** 
- [ ] Decide when, where, how to review and define our updated practices 
- [ ] Run sessions to capture the pulse of our design research practice now
- [ ] Create GH issues to capture the work that needs to be done to make our guidance consistent with our practices and intent

**Tasks**
- [ ] 
- [ ] 

**Definition of done**
- [ ]  One of the POs has approved the change
- [ ]  Outreach approval (if needed)

**Comment by bpdesigns** [comment]
Reviewed in backlog grooming. 

Issue looks clear but will need to be broken down into smaller issues so it can be completed within a week

**Comment by MelissaBraxton** [comment]
@bpdesigns  - I think this might be dependent on [#584](https://github.com/18F/methods/issues/584).  What do you think?

**Comment by bpdesigns** [comment]
I agree @MelissaBraxton it's dependent on #584

**Comment by bpdesigns** [comment]
"Relevant to other Guides" If we can document a repeatable practice for our products to be up to date representations of how we work.
