### ISSUE TITLE
Offboarding issue for Eleni

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/ux-guide#315]
# Tasks
## For whoever manages mtg invites at the moment
- [x] Remove them from Adventures in coworking meeting invites
- [x] Remove from [“who’s on the team” section of README](https://docs.google.com/document/d/1dRKIZld_QmohUeDLQ8RbiHTweqHsJEjsn2akNMzQRUI/edit#bookmark=id.y4t1lhlwws4z)

## For person offboarding
- [x] Unassign yourself from any issues you may be assigned to. If you can, drop a note in the channel to let folks know someone might need/want to pick them up!
- [x] Remove yourself from the channel #co-working-adventure, or stick around and lurk! It’s up to you!
