### ISSUE TITLE
Document PR approval process

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/ux-guide#32]
The current contributing guide is specific to original authors internal to 18F. We need to update to be geared toward public contributors who may be outside of 18F or even outside government.

**Acceptance criteria** 

**Tasks**
- [x] Review existing PR approval process examples
- [x] Determine needed approvals (outreach?)
- [x] Draft instructions for the approval process
- [x] Publish PR approval process on GitHub

**Definition of done**
- [x]  PO approval

**Comment by MelissaBraxton** [comment]
Consider reviewing examples first 
 - Open Forest has a few good examples

**Comment by NorahMaki** [comment]
Draft here: https://docs.google.com/document/d/1Nd5HOUDv-qjWs6yBPVrESJf2cPzXGU5xdUajznHibvA/edit#
