### ISSUE TITLE
Publish content on recruiting with communities and nonnative English speakers

### ISSUE THREAD

**Issue by bpdesigns** [18F/ux-guide#320]
**Background**
In the UX guide section on Recruiting there should be guidance about partnering w/ community organizations to connect with historically marginalized groups or how we can do better at recruiting nonnative english speakers and when we might need to that. 
**Acceptance criteria** 
- [x] Update the UX Guide [Participants and recruiting](https://ux-guide.18f.gov/research/plan/#participants-and-recruiting) section to include rpartnering w/ community organizations to connect with historically marginalized groups
- [x] Update the UX Guide [Participants and recruiting](https://ux-guide.18f.gov/research/plan/#participants-and-recruiting) section to include recruiting nonnative English speakers 

**Tasks**
- [x] Research and review the work we've done in these area's at 18F 
- [x] Create a doc with draft content and ask for review. 
- [x] Once reviewed update the content in github and tag @bpdesigns and @MelissaBraxton for review
- [x] Share the content with the two usa.gov and vote.gov folks who shared their best practices.

**Definition of done**
- [x]  One of the POs has approved the change
- [ ]  Outreach approval (if needed)

**Comment by amandarkennedy** [comment]
In the spirit of working in the open, I started a Google doc that includes some to-do items and a WIP draft of the content updates: https://docs.google.com/document/d/1pDrz16ey7o1j1T3XpI_2wBvzGcTMnPEZhRNsLtLqeyI/edit?usp=sharing

I have also started scheduling 1x1s with various folks from usa.gov and vote.gov!

**Comment by amandarkennedy** [comment]
Cross-posting from Slack: 

I have drafted some initial content in a Google Doc [here](https://docs.google.com/document/d/1pDrz16ey7o1j1T3XpI_2wBvzGcTMnPEZhRNsLtLqeyI/edit#bookmark=id.6hx2iyxdhvhk). I have some conversations set up with folks from vote.gov and usa.gov in the coming days, but in the meantime, I would be interested in getting some initial feedback on the content.

- I have made some suggested edits to the existing "**Identifying target groups**" section that are relevant to mitigating bias and stigma for underserved communities.

- I have also added new sections: **Creating a screener**, **Outreach methods**, and **Considerations for recruiting underserved communities**. The first two sections are broader and slightly beyond the scope of issue #320, but they do speak to important steps for recruitment, especially if we are doing more public-facing user research in general.

I'd love some initial feedback on a.) whether the structure and sequence of these sections makes sense and are worth including and b.) the content itself. If anyone has time to provide feedback in the doc by ~EOD Monday, Jan. 30, I would appreciate it! I will then incorporate learnings from the vote.gov and usa.gov folks later on and will request another round of edits. Thanks!

**Comment by bpdesigns** [comment]
@amandarkennedy I can't remember if I shared this resource with you earlier. The wiki from the [10x project on Equity Centered Design with Tribal Nations](https://github.com/GSA-TTS/10x-Equity-centered-design-with-American-Indians-and-Alaska-Natives/wiki/Considerations-for-engaging-communities-with-respect). that I worked on in 2021 has some content related to this. The wiki acts as a bit of a guide.

**Comment by amandarkennedy** [comment]
Content is ready for review! https://docs.google.com/document/d/1pDrz16ey7o1j1T3XpI_2wBvzGcTMnPEZhRNsLtLqeyI/edit?usp=sharing

**Comment by amandarkennedy** [comment]
We got lots of great feedback during research guild on Friday! Incorporating it this morning.

**Comment by MelissaBraxton** [comment]
Revised issue title to make it actionable.

**Comment by amandarkennedy** [comment]
@MelissaBraxton @bpdesigns I have resolved comments, and it is ready for another review here! https://docs.google.com/document/d/1pDrz16ey7o1j1T3XpI_2wBvzGcTMnPEZhRNsLtLqeyI/edit#

the only comment I didn't resolve was the one about tone — not sure how to account for that, or if it is okay as is. If it is still too formal, it would probably require another pass by someone else since I don't quite have the time at the moment.

**Comment by christophermather** [comment]
Per 2/14/2023 action moving this to "Done", also marking this as "complete".
