### ISSUE TITLE
Consider new section(s) in the UX guide that addresses how we account for neurodiversity in our research practices

### ISSUE THREAD

**Issue by bpdesigns** [18F/ux-guide#324]
**Background**
Neurodiversity is an increasingly important issue that we need to address while preparing to conducting user research.

**Acceptance criteria** 
- [ ] references to how Neurodiversity should hat inform how we do research
- [ ] specifically include the term Neurodiversity in the text so that its searchable and findable by 18F and the public. 

**Tasks**
- [ ] research how the spectrum of Neurodiversity and what could change about how we do research to better accommodate it in research participants and teammates 
- [ ] review the UX guide for places to include updated text. Consider if a new section or page would be useful or if content should fit within existing topic areas.
- [ ] draft new content. Use a doc for the draft if large sections of content will be included or change. A pull request of inline text edits is fine for places where a word or few sentences would change. As part of content approval, share draft content in the TTS slack #g-diversity channel for awareness and review. 
- [ ] once content is approved update the content in the repo.  

**Definition of done**
- [ ]  One of the POs has approved the change
- [ ]  Outreach approval (if needed)

**Comment by bpdesigns** [comment]
@MelissaBraxton drafted issue based on our conversation for your input.

**Comment by katefisher808** [comment]
@bpdesigns @MelissaBraxton - I tagged myself into this one today! I haven't started yet though. I'll send you a slack message tomorrow or Monday to see if you want to chat through it first.

**Comment by MelissaBraxton** [comment]
Hey there, @katefisher808 is this one still in progress? Is there any support you need to move it forward?

**Comment by katefisher808** [comment]
Sorry for my ambitiousness on this one! I self-assigned but then never was able to tackle it due to some of the other priority issues. I unassigned myself.

**Comment by MelissaBraxton** [comment]
Hey there, @bpdesigns!   We think this is a good idea but it doesn’t currently fit with our near- or mid-term roadmap. This means we will not work on this in the next 3 months, so we're going to icebox it for now. 

We will revisit this in 3 months and check in then. In the meantime, if you find another way to get this work done feel free to choose that path. If you do find a different path to getting the work done and no longer want TLC crew help, please remove the issue from our project board.
