### ISSUE TITLE
Update language on working with partners part 1

### ISSUE THREAD

**Issue by bpdesigns** [18F/ux-guide#325]
**Content change needed.**
The "[Meet partners where they are](https://ux-guide.18f.gov/our-approach/meet-partners-where-they-are/)" section is primarily about maturity of the partner and collaboration tools. 

**Describe the change you'd like to see**
This page should also describe how to engage with the partner across the design process. 

**Acceptance Criteria**
- [ ] content is reviewed and changes needed are scoped for the UX Guide

**tasks**
- [x] review and align with Delivery School content
- [x] earmark the things that are out of date (wrong) and need to be updated
- [ ] list the changes needed to scope ux guide content

**Additional context**
- There are two pages in the TTS handbook that talk about how partnership. Consider if these should be linked to or updated as part of the process. 
- Part two of this update #376 

Related TTS Handbook pages:
- [Consulting with partners](https://handbook.tts.gsa.gov/18f/projects-partners/how-we-relate-to-partners/)
- [How we collaborate](https://handbook.tts.gsa.gov/general-information-and-resources/how-we-collaborate/#are-there-times-we-shouldn-t-collaborate-with-our-partners)

**Add reviewers** 
@bpdesigns 
@MelissaBraxton

**Comment by lauranash18f** [comment]
Delivery school content is back in the hands of leadership — but I have reviewed in context of some of the discussions, and have identified a few pages to focus on. I've set time aside this afternoon for heads down writing on this.

**Comment by lauranash18f** [comment]
This is outlined in this doc: https://docs.google.com/document/d/1jpII1Bzq6cOoz1XhFiZKYG3oFf3QukuRd-rTJ7-QzZA/edit

Pages to update include

*UX Guide*
- Meet Partners where they are
- Defining design

*Handbook*
- Consulting with partners

**Comment by christophermather** [comment]
Per action on 3/7/2023 moving this to "Done", also marking this as "closed"
