### ISSUE TITLE
Coding research data

### ISSUE THREAD

**Issue by bpdesigns** [18F/ux-guide#326]
**Current state**
The 18F UX guide talks about going from [*data to insights*](https://ux-guide.18f.gov/research/make-research-actionable/#from-data-to-insights) and *De-identifying data* but it does not describe how to do so. 

**Recommended update**

**Acceptance criteria _(we'll know we're done when…)_** 
- [ ] describe in more detail 18Fs basic practices for coding and de-identifying research data.

**Tasks**
- [ ] describe how to code research data
- [ ]  PO review @bpdesigns @MelissaBraxton

**Comment by bpdesigns** [comment]
@boonerang @MelissaBraxton @annepetersen for your awareness and comments.

**Comment by MelissaBraxton** [comment]
Could this be a method? Does this belong in the guides or the methods.

**Comment by bpdesigns** [comment]
@MelissaBraxton I think this makes sense as a Method. Closing this issue
