### ISSUE TITLE
Publish release notes for December

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/ux-guide#330]
**Background**
We want to keep visitors apprised of changes we're making on a sprintly basis!

**Acceptance criteria _(we'll know we're done when…)_** 
- [x] Release notes for changes that have been made to the 18F Methods site in December are publicly available 
- [ ] Release notes for changes that have been made to the UX Guide site in December are publicly available 

**Tasks**
- [x] Review release notes documentation [here](https://github.com/18F/methods/wiki/Releases#how-to-make-a-new-release)
- [x]  Write 18F Methods release notes
- [x]  Write UX Guide release notes
- [x]  PO review

**Comment by MelissaBraxton** [comment]
We want to use a 2 week cadence for release notes, but since we haven't issues any since we started our co-working adventure, this release covers a longer timeframe.

**Comment by MelissaBraxton** [comment]
We decided to move to a monthly cadence for release notes, and I updated the wiki page to reflect this.

**Comment by christophermather** [comment]
This is marked as "Done". Also marking as "Closed"
