### ISSUE TITLE
Update UX Guide resource page

### ISSUE THREAD

**Issue by bpdesigns** [18F/ux-guide#331]
**Background**
 The Resource page of the UX guide is outdated

**Acceptance criteria** 
- [ ] content should be up to date 
- [ ] content should be what is expected when looking for ux design research resources 

**Tasks**
- [ ] review the page for outdated content and links to outdated content
- [ ] update content to be current
- [ ] remove content that is not specifically a ux design research resource

**Definition of done**
- [ ]  One of the POs has approved the change
- [ ]  Outreach approval (if needed)

**Comment by AnitaYCheng** [comment]
Another consideration (observed while replatforming), is that the internal resources in the UX Guide are _very_ extensive. Much more so than in other guides. It's hard to find these internal resources if we leave them in the homepage side-nav, where the "Resources" are for other guides.
