### ISSUE TITLE
remove references to Federalist  - Review UX Guide and Methods site links

### ISSUE THREAD

**Issue by bpdesigns** [18F/ux-guide#333]
**Point of contact**
@MelissaBraxton or @bpdesigns 

**Background**
In Dec. 2022, we migrated both the UX Guide and Method cards to CG Pages. There are likely some references to Federalist as a means of previewing the site lingering in either the UX Guide or Methods repos. This issue covers removing outdated references to previewing either site on federalist and replacing them with references to Pages where it's relevant. 

**Acceptance criteria** 
- [ ] Neither site contains an outdated federalist preview reference

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

**How much time do you anticipate this work taking?**
1 day

**Tasks**
- [ ] Review Methods site and documentation in GitHub and replace federalist refs w/ pages preview links.
- [ ] Review UX Guide site and and documentation in GitHub and replace federalist refs w/ pages preview links.

**Definition of done**
- [ ]  One of the POs has approved the change

**Comment by katefisher808** [comment]
@bpdesigns and @MelissaBraxton  

Take a look at the instances + suggested actions below for your review:

1. 18F Methods: Personas
Where: [Persona method page](https://methods.18f.gov/decide/personas/) 
Suggested change:"_Personas for Federalist_" adjusts to "_Personas for Cloud.gov_" without changing the github repo title "federalist-design" and the [URL](https://github.com/18F/federalist-design/wiki/Personas)

2. UX-Guide: Resources
Where: [Overview > Resources page](https://ux-guide.18f.gov/resources/)
Suggested change: "_Cloud.gov Pages (formally Federalist)_" adjusts to "_Cloud.gov Pages_"

3. UX-Guide: Meet partners where they are
Where: [Our approach > Meet partners where they are](https://ux-guide.18f.gov/our-approach/meet-partners-where-they-are/)
Suggested change: "_Cloud.gov Pages (formally Federalist)_" adjusts to "_Cloud.gov Pages_"

4. UX-Guide: Build a Prototype
Where: [Design > Build a prototype](https://ux-guide.18f.gov/design/build-a-prototype/)
Suggested change: Swap all "Federalist" for "Cloud.gov"
Question: there is a link to join the public channel #federalist-support, which still exists. Should we put in a new ticket to change the name of this channel? It only has 4 members

**Comment by MelissaBraxton** [comment]
Thanks so much Kate! 

These all sound good to me!

 - I can approve the suggested change on **1,** if you want to open a pull request.
- I'll defer to @bpdesigns on **2-4**. 
- On **4,** I'd suggest changing it to #cg-pages, as that's where folks go for pages support now.

**Comment by katefisher808** [comment]
Thank you @MelissaBraxton! 
@bpdesigns I'll keep an eye out for your input on 2-4.

**Comment by bpdesigns** [comment]
Thanks @katefisher808 ! I concur with @MelissaBraxton on #cg-pages. All other changes sound good.
