### ISSUE TITLE
Link to TTS Handbook research compensation process

### ISSUE THREAD

**Issue by bpdesigns** [18F/ux-guide#337]
**Background**
There are details about the research compensation process in the TTS Handbook and 18F UX Guide. The handbook should be the source of truth so if it changes content only needs to be updated in one place. 

**Acceptance criteria _(we'll know we're done when…)_** 
- [ ] Evergreen text about research compensation and why we do it remains in the 18F UX Guide 
- [ ] Detail about the compensation process are removed from the 18F UX Guide 
- [ ] Every place the 18F UX guide talks about research compensation should link to the handbook

**Tasks**
- [x] Retain evergreen text about research compensation and why we do it in the 18F UX Guide, rewrite text as necessary to make it evergreen 
- [x] Remove detailed information about the compensation process from the 18F UX Guide 
- [x] Review recommendations re: Methods compensation card link (#568) and implement change
- [x] link to the handbook research compensation process in every place the 18F UX guide that mentions compensation 
- [ ]  PO review [if task involves content changes] 
- [ ]  Outreach approval [if needed]

**Comment by claireb-gsa** [comment]
Started a draft document - [Content update - compensation mention in UX guide - 2023-01 - ux-guide #337](https://docs.google.com/document/d/1TgzFVrIRn-T00tvbh_hJlshqBblLKda1FEgHulNDnbo/edit#)

**Comment by claireb-gsa** [comment]
Edits to the UX Guide and Methods are both in PRs awaiting review and approval.

**Comment by MelissaBraxton** [comment]
I think just needs a review and merge by @bpdesigns?

**Comment by bpdesigns** [comment]
Thanks for the nudge @MelissaBraxton
