### ISSUE TITLE
Don't put external link icons on links in the footer

### ISSUE THREAD

**Issue by mgwalker** [18F/ux-guide#339]
**Background**

The method we use for marking external links is a bit too aggressive and captures links in the footer as well. It should not.

**Acceptance criteria _(we'll know we're done when…)_** 
- [ ] links in the footer do not include the "external link" icon
- [ ] all other links that leave the UX guide do still have the icon

**Tasks**
- [ ] update the script that identifies external links to exclude links in the footer
- [ ] PO review
