### ISSUE TITLE
Update automated test documentation

### ISSUE THREAD

**Issue by mgwalker** [18F/ux-guide#344]
**Background**

The [automated testing](https://github.com/18F/ux-guide/wiki/Automated-testing) wiki is outdated now. It was outdated within a couple of days of being written. 🤦🏻‍♂️ 

**Acceptance criteria _(we'll know we're done when…)_** 
- [x] The wiki accurately reflects the kinds of tests that are run
- [x] The wiki accurately describes how to understand the test outputs

**Tasks**
- [x] Update the stinkin' wiki

**Comment by mgwalker** [comment]
@MelissaBraxton Here's a pass at making the tests documentation better, too: https://github.com/18F/ux-guide/wiki/Automated-testing

**Comment by MelissaBraxton** [comment]
LGTM! Very clear. I think we can call this done. :)
