### ISSUE TITLE
Document site architecture in wiki

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/ux-guide#353]
**Background**
We want to document the site architecture in the wiki to help folks working on the site get oriented and up-to-speed quickly. 

**Acceptance criteria _(we'll know we're done when…)_** 
- [ ] The site architecture is live on the wiki
- [ ]  An engineer unfamiliar with the project can understand the site architecture after viewing the wiki content

**Tasks**
- [ ] Draft architecture diagram
- [ ]  PO review [if task involves content changes] 
- [ ] Post architecture documentation to the wiki
- [ ]  Accessibility review
