### ISSUE TITLE
Best practices on working with different communities in the research process

### ISSUE THREAD

**Issue by bpdesigns** [18F/ux-guide#360]
**Background**
There is no current established practice on researching with communities at 18F. We need to document what GSA and TTS has put forward about this and how to operationalize within the 18F research practice through the 18F UX Guide.

We have already updated the Plan section of the UX guide with considerations for recruiting communities (see https://github.com/18F/ux-guide/issues/320). Now, we have an opportunity to expand on these emergent practices throughout the rest of the guide.

**Acceptance criteria**

- [ ]  Update the UX Guide [Make research actionable](https://ux-guide.18f.gov/research/make-research-actionable/) section with content on how best to responsibly and effectively share/socialize research findings with team members, stakeholders, and the public  

**Tasks**
- [x]  Review relevant resources below.
- [x] Identify if there are other communities with unique considerations for how best to engage with them in the research process and describe an approach to working with them. 
- [x] Create a doc with draft content and ask for review in #g-research and #18f-design
- [ ] Determine if there are any other subject matter experts who should be included in the review process, and name them here.

Create a new issue to cover:
- [ ] Refining content based on feedback 
- [ ] Creating a pull request to update the content in github and tag @bpdesigns and @MelissaBraxton for review.

**Relevant resources**

- [x]  [Considerations for engaging communities with respect](https://github.com/GSA-TTS/10x-Equity-centered-design-with-American-Indians-and-Alaska-Natives/wiki/Considerations-for-engaging-communities-with-respect)
- [x] [Deck on recruiting for research within disability community](https://docs.google.com/presentation/d/14nTo_YRmp2LjFm33GHW5zRY5iTSkfEHv91tHLo6b5Qk/edit#slide=id.g153d5c180e0_0_0)
- [x] DEIA Growth for Teams - [Defining and Identifying Underserved Communities for User Research](https://docs.google.com/document/d/1VQtwLrpheDWX24GyeOKmaa_cGMowW7ywcEpNHtJ4eOw/edit#heading=h.gvyc8w8d9zx9)

**Definition of done**
- [ ]  One of the POs has approved the change
- [ ]  Outreach approval (if needed)

**Comment by bpdesigns** [comment]
@amandarkennedy can you review this issue we discussed yesterday? 
- One thing needed to be added is the list of specific resources we want someone to reference when picking this up.
- I'd also like your feedback if you think this could be split into more tasks.

**Comment by amandarkennedy** [comment]
@bpdesigns will do! I am wrapping up initial suggested edits for #320 and will then focus on this issue next.

One current thought is that we can remove:
>  - [ ] review current content on participant engagement and research recruiting in the 18F UX Guide

because that is already covered in #320. What do you think?

**Comment by bpdesigns** [comment]
@amandarkennedy re: #320 - that makes sense to me!

**Comment by amandarkennedy** [comment]
How I'm thinking of re-scoping this issue into more specific issues:

**Include co-design approaches and resources under the "Do" section:**
- We could decide how to best frame co-design within the guide since since we typically have not conducted co-design activities but want to move in that direction. 
- We could use the upcoming [design principles](https://docs.google.com/document/d/1o8RIEwRFGXtxgO6g_NyI0STFH4LJ-2CF_Oc9dJq0sQ8/edit#) to help determine that framing, and reference some of GSA's long-term goals in the [Equity Action Plan](https://www.gsa.gov/cdnstatic/GSAEquityPlan_EO13985_2022.pdf) as our North Star.
**Include considerations regarding communities in the  "Make research actionable" section**
- This part could include aspects like data collection and representation (both referenced referenced [here](https://github.com/GSA-TTS/10x-Equity-centered-design-with-American-Indians-and-Alaska-Natives/wiki/Considerations-for-engaging-communities-with-respect)), and sharing out findings with communities. 

Am I missing any other key topics that are not represented above or in the #320 content? For each issue, I can also include the list of resources that have been shared with me and which might be most relevant to the topic at hand.

**Comment by bpdesigns** [comment]
@amandarkennedy those all sound like good ideas to me :) 

We haven't had a blog post issue yet - but I like the idea of it. Having it as an issue would make it a topic for discussion in sprint planning

**Comment by MelissaBraxton** [comment]
Hey there @austinhernandez  - Looking at the size of this, I think we should break it up. I think the background reading and research part is a good first issue here. You want to split out drafting and implementing the content as a separate issue?

**Comment by austinhernandez** [comment]
[Here is the WIP document](https://docs.google.com/document/d/1HYBvaQVxg0YZZNps5hAMkDOncL1Ucq5aFwofxv5W1iM/edit?usp=sharing)

**Initial thoughts and questions:**
- Communities is a large umbrella term and has a ton of interpretations
   - Is this meant to be "historically marginalized" communities?
   - Is this communities we work with frequently that aren't necessarily marginalized (e.g. active military, parents, tech professionals)?
- How to integrate with the UX Guide, specifically the [make research actionable page](https://ux-guide.18f.gov/research/make-research-actionable/) 
   - How are people using the guide? is a separate section the best way to integrate best-practices?
 
I spoke to @bpdesigns 4/6 (and we will be meeting again 4/11) to discuss these questions and there seems to be a few emergent themes and overlaps with inflight work:

- Addressing specific communities that historically marginalized that are particularly relevant to work as a federal agency
  - Tribal Nations and/or American Indians/Alaska Natives
  - People with disabilities
  - [Underserved communities](https://www.whitehouse.gov/briefing-room/presidential-actions/2021/01/20/executive-order-advancing-racial-equity-and-support-for-underserved-communities-through-the-federal-government/)
- Addressing ethics, equity, and intersectionality included at all points of how we do research
   - In addition (or instead of) a separate [make research actionable page](https://ux-guide.18f.gov/research/make-research-actionable/) adding specific considerations of things like compensation, data privacy, presenting findings, etc. when working with historically marginalized communities 
- Internal workshops or team exercises as pre-work to working with historically marginalized communities 
   - Power dynamics
   - Helping or hurting?
- Overlap/adjacent themes and work
   - Accessibility 
      -  https://github.com/18F/delivery-assurance/issues/91 
      - https://github.com/18F/delivery-assurance/issues/87
   - #312 
   - #291 
   - [DEIA Action Guide for Teams](https://docs.google.com/document/d/1VQtwLrpheDWX24GyeOKmaa_cGMowW7ywcEpNHtJ4eOw/edit#)

**Next steps:** 

- [ ] Complete draft and share with Ben and Melissa
- [ ] Address concurrent work / Combine inflight work
- [ ] Split out drafting and implementing the content as a separate issues

**Comment by MelissaBraxton** [comment]
Sounds like a great plan, @austinhernandez!

**Comment by MelissaBraxton** [comment]
Related to issues #312 and #401. But the scope here is an initial outline/draft, but we should take a look at 312 and 401 when it comes to documenting follow on work, as some of it might belong under the work spelled out in those issues.

**Comment by bpdesigns** [comment]
@MelissaBraxton let me know if you'd like me to break these tickets into two. Perhaps they could each have a "draft content" and an "implement" ticket?

**Comment by MelissaBraxton** [comment]
Thanks @bpdesigns  - Let's hold off for now. For now, I prefer creating follow on issues for the implementation work as a task on the content drafting ticket. That way the person who works on the drafting issue can carry over any additional relevant context, and the implementation work is documented just-in-time/not before we could reasonably pick it, given the dependency that would always be inherent in those kinds of issue pairs.

**Comment by bpdesigns** [comment]
sounds good.

**Comment by austinhernandez** [comment]
i have imparted my subject matter expertise to specifically address the AC of this ticket to: "Update the UX Guide [Make research actionable](https://ux-guide.18f.gov/research/make-research-actionable/) section with content on how best to engage and work different communities through the research process." it's been looked at by @donnykwan @evoeges and @jduss4 and posted on the g-research and 18f design slack channels for feedback. 

However, it's my profesh opinion that best-practices working with different [underserved / historically marginalized] communities happens across other sections of the UX guide, specifically earlier in the process in the `plan` or `do` processes. There's even nuggets of wisdom i have for the `bias` and `ethics` section. but fear not! there are other tickets in place to address this very issue. 

The document for this ticket is here [Make research actionable: Best practices on working with different communities in the research process](https://docs.google.com/document/d/1HYBvaQVxg0YZZNps5hAMkDOncL1Ucq5aFwofxv5W1iM/edit?usp=sharing).

I also made a [Best practices on working with different communities in the research process notes doc](https://docs.google.com/document/d/1E7_X4ty2PFbI50UgXRQUZmVXyWhDNls0M7Q1yiDfvdc/edit?usp=sharing) that I can use to incorporate my findings throughout the UX guide and [DEIA Action Guide](https://docs.google.com/document/d/1VQtwLrpheDWX24GyeOKmaa_cGMowW7ywcEpNHtJ4eOw/edit#).

**Comment by MelissaBraxton** [comment]
@austinhernandez  -  I see in the doc there are places you've asked for input from reviewers. Proposed next steps: 

- [ ] @bpdesigns reviews / addresses Qds in the doc (looping in additional reviewers from #g-research and/or #g-diversity as needed)
- [ ] @austinhernandez creates a PR for these suggested changes
- [ ]  @austinhernandez creates a new issues for weaving in edits to other guide sections

How does this sound as a path to getting this to done? 

If this sounds ok, then I think we can move this into **in review** and tag Ben in is a reviewer?

**Comment by bpdesigns** [comment]
@MelissaBraxton I'll review by EOD.

**Comment by MelissaBraxton** [comment]
hey there, @austinhernandez  - Chatted w/ Ben and if you could be the one to create a PR to revise the "making research actionable" page, that way @bpdesigns can review and approve the PR.
