### ISSUE TITLE
Determine how we use milestones

### ISSUE THREAD

**Issue by bpdesigns** [18F/ux-guide#361]
POs to review this github feature and set short term (3month) goals. Product roadmap even?

**Comment by MelissaBraxton** [comment]
- [ ] Determine the timeframe for milestones
- [ ] Lay out goals associated with M1... anything else goes into a "later" pile
- [ ] Create M1 in GH, include goals in def
- [ ] Document in the wiki how we use milestones in the wiki

**Comment by MelissaBraxton** [comment]
Added some MVP documentation here: https://github.com/18F/methods/wiki/Guiding-principles-and-practices#labels--milestones

@bpdesigns - take a look! When you're good with it, and when you've added relevant milestone tags to UX Guide issues, I think we can close this out. I'll take myself off of the issue, as you can take it from here!

**Comment by bpdesigns** [comment]
LGTM! I'll work on adding the tags to the UX Guide

**Comment by bpdesigns** [comment]
Arching as as won't fix because we're changing how we collaborate across teams.

**Comment by christophermather** [comment]
Flagged as "won't fix" in prior comment. Marking as "Closed" now
