### ISSUE TITLE
Add foundational description of what are equitable research practices and how to use them.

### ISSUE THREAD

**Issue by amandarkennedy** [18F/ux-guide#364]
**Background**
While previewing #320 content in research guild, we received a great suggestion: Set the stage for equitable research considerations in the "[Clarifying the basics](https://ux-guide.18f.gov/research/clarify-the-basics/)" section. Now that we are adding more content related to doing research with communities throughout the guide, this particular addition will lay that foundation.

**Acceptance criteria**
- [ ] Update the "[Clarifying the basics](https://ux-guide.18f.gov/research/clarify-the-basics/)" section of the UX guide to introduce that we will be including equitable research considerations throughout the guide. Potentially this could include a sentence under "What it is" and a sentence under "Good practices."
- [ ] 18F ux guide 

**Tasks**
- [ ] Create a doc defining equitable research practices and how to use them. 
- [ ] Identify where the text should live in the ux guide
- [ ] Ask for review in #g-research and #co-design
- [ ] Once reviewed update the content in github and tag @bpdesigns and @MelissaBraxton for review.

**Definition of done**
- [ ] One of the POs has approved the change
- [ ] Outreach approval (if needed)

**Comment by bpdesigns** [comment]
@amandarkennedy can you identify where on the **Clarifying the basics** page this content should live?

My initial thought would be a sentence under "What it is" and a sentence under "Good practices."

**Comment by amandarkennedy** [comment]
Hi @bpdesigns! :) Good question. Those seem like the most instinctive places to put it!

**Comment by bpdesigns** [comment]
Thanks @amandarkennedy I updated the ticket to reflect that.

**Comment by bpdesigns** [comment]
archiving this as duplicative of the Ethics page updates #412
