### ISSUE TITLE
Fix broken links in privacy section

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/ux-guide#365]
**Point of contact**
@MelissaBraxton or @bpdesigns 

**Timeline**
Does this need to happen in the next two weeks?

- [X] Yes
- [ ] No

**How much time do you anticipate this work taking?**
A day or two

**Background**
There are a few mentions of PIAs and a broken link in the [privacy section](https://ux-guide.18f.gov/research/privacy/) and in the privacy part of the resources page [here](https://ux-guide.18f.gov/resources/#privacy-and-informed-consent). 

**Acceptance criteria _(we'll know we're done when…)_** 
- [x] Any links in that section work and bring users to current relevant content
- [x] We've removed any mention of PIA that is no longer relevant

**Tasks**
- [x] Review section
- [x] remove or revise out-of-date content and broken links
- [x] Refine recommended links changes/updates based on input 
- [x] Create a PR to implement changes
- [x] Accessibility review [if needed]
- [x]  add @bpdesigns and @MelissaBraxton as reviewers

**Comment by annepetersen** [comment]
Bumped into this as a problem today. This does not work: [Privacy Impact Assessment for Design Research](https://www.gsa.gov/cdnstatic/20181022%20-%20Design%20Research%20PIA_posted%20version.pdf)(external link)) and folks need it for our work.

**Comment by janelx** [comment]
Unclear about this acceptance criteria: " We've removed any mention of PIA that is no longer relevant" @MelissaBraxton @bpdesigns what PIA is no longer relevant? Should I remove all references to it?

**Comment by MelissaBraxton** [comment]
@dluetger - Ben and I were recalling that you may know where to look for the latest guidance on PIA and the decision by our privacy office that it's no longer needed. Would you be able to sync up w/ @janelx  to update this section?

**Comment by dluetger** [comment]
I can see what I can remember but sure thing

**Comment by janelx** [comment]
Quick update: here are broken links and suggested edits ([google doc](https://docs.google.com/document/d/1IKP6-HnONO6e4pbJ9N5MlYBijmUPjq7YyFsuNM9t3m4/edit?usp=sharing).I still need to follow up with @dluetger about the PIA changes.

**Comment by janelx** [comment]
@MelissaBraxton I haven't been able to find out much about an update PIA policy, otherwise the doc is ready for PO review.

**Comment by MelissaBraxton** [comment]
Thanks, @janelx - I took a look and added some comments. 

Here is the thread where research guild leaders talk about the fact that we no longer need a PIA for design research. We need to remove all reference to PIA and process re: updating and/or maintaining a PIA for design research. 

https://gsa-tts.slack.com/archives/CGFKUN8CF/p1672244074601319

**Comment by MelissaBraxton** [comment]
@janelx  - I added to the task check list what's next in getting this to done!

**Comment by bpdesigns** [comment]
@janelx @MelissaBraxton the r-guild was able to get the [Privacy Act Statement for Design Research
](https://www.gsa.gov/reference/gsa-privacy-program/privacy-act-statement-for-design-research) updated

**Comment by MelissaBraxton** [comment]
Hi @bpdesigns  - Looks like this was just updated yesterday! I'm surprised because I'd thought the guild had determined we didn't need one? Is the recommendation then to keep references to PIA and just update the links to the new PIA?

**Comment by bpdesigns** [comment]
Fixed by #403
