### ISSUE TITLE
Introduce Service Design in the UX Guide

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/ux-guide#371]
**Background**
The 18F service design practice area needs to document our practices. Goals:
1. help ensure consistency in how we practice service design at 18F
2.  help better tell the story of the fact that service design is one of our practice areas to external audiences to the end of engaging ( a) partners who may be interested in service design services and (b) service designers who may be interested in joining 18F. 

**Acceptance criteria _(we'll know we're done when…)_** 
- [x] We have content drafted for the UX Guide that accurately reflects 18F's service design practice.

**Tasks**
- [x] Determine where in the UX Guide SD content should live (may warrant mention in multiple sections!) 
- [x] "service design" as a word that shows up in SEO
- [x] Draft content in a GDoc
- [x] SD working group reviews
- [x] @bpdesigns reviews

**Reviewers**
- [x] SD team
- [x] @MelissaBraxton, @bpdesigns

**Comment by bpdesigns** [comment]
Initial goal - use the words "Service design" somewhere right now so our service design practice area and lens can be searched.

**Comment by katefisher808** [comment]
OK great! I just moved it to 'in progress' for you and Laura as the assigned on it move it through the remaining DA steps. Thanks both.

**Comment by MelissaBraxton** [comment]
@bpdesigns  - [Here's the draft.](https://docs.google.com/document/d/1wNBZoftlRvJbLK-5uazsQOG_2HpPMyLjmAHSGLOCBpU/edit#) Laura, Elisa, and i have already done a first pass, so I think it's ready for your review!

**Comment by MelissaBraxton** [comment]
Moving to done. @bpdesigns created [this issue](https://github.com/18F/ux-guide/issues/397) to implement the content.
