### ISSUE TITLE
Set up milestone syncing

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/ux-guide#374]
**Background**
We just started using milestones! But it doesn't look like they sync across repos. This issue covers implementing milestone syncing so that we can easily apply the same milestones to both the UX Guide and the Methods to help keep our work aligned.  We created a milestone in the Methods repo, but we want it to also appear in the UX Guide repo. 

**Acceptance criteria _(we'll know we're done when…)_** 
- [ ] implementing milestone syncing

**Tasks**
- [x] review syncing across repos documentation from [wiki](https://github.com/18F/methods/wiki/Syncing-across-repos)
- [ ] possibly pair with an engineer 
- [ ]  PO review [if task involves content changes] 
- [ ]  Accessibility review [if needed]
- [ ]  Outreach approval [if needed]

**Comment by mgwalker** [comment]
@MelissaBraxton @bpdesigns For a first pass, is it sufficient that creating a milestone in repo A also creates the milestone in repo B? That is relatively simple. If you also want to keep milestone descriptions and open/close status in sync, that's possible but a bit more effort.

**Comment by bpdesigns** [comment]
@mgwalker yes. that works.TY!

**Comment by bpdesigns** [comment]
@mgwalker I was wrong in my comment earlier :( this is not syncing milestones to the UX Guide. Any thoughts? I'll create a DA Team issue on this if you do not have time to take a look. TY!

**Comment by mgwalker** [comment]
Can you describe more what you expect to happen? As best I can tell, there haven't been any milestones created in either repo since the synchronization automation was merged. The automation only syncs when milestones are created. So it's less of a synchronization and more of a... push? Any milestones that existed when the automation was merged would need to be manually copied over.

**Comment by bpdesigns** [comment]
There are milestones in the Methods issues [(see this example)](https://github.com/18F/methods/issues/595). I would expect to show up in UX Guide issues that I could select within the ticket [(see this example)](https://github.com/18F/ux-guide/issues/388). 

Okay. So maybe the issue here is that the Methods site had a milestone before the syncing was created so would have needed to be moved manually. BUT if I create a new milestone now it should be copied over - is that right?

**Comment by mgwalker** [comment]
I believe the second paragraph is correct.

I'm not sure what you mean in the first paragraph.
