### ISSUE TITLE
Part 2 Intro service design to UX guide

### ISSUE THREAD

**Issue by bpdesigns** [18F/ux-guide#375]
**Background**
The 18F service design practice area needs to document our practices. Goals:
1. help ensure consistency in how we practice service design at 18F
2.  help better tell the story of the fact that service design is one of our practice areas to external audiences to the end of engaging ( a) partners who may be interested in service design services and (b) service designers who may be interested in joining 18F. 

**Acceptance criteria _(we'll know we're done when…)_** 
- [ ] We have content live in the UX Guide that accurately reflects 18F's service design practice.

**Tasks**
- [ ] Invite 18F SD working group to review - reach out in the #18F-service-design Slack channel!
- [ ] Writing lab /plain language review
- [ ] Create a PR to implement the content changes
- [ ]  PO review

**Comment by christophermather** [comment]
This was moved to "Done" on May 9, 2023. Also closing now.
