### ISSUE TITLE
Add PRA guidance to the 18F UX Guide

### ISSUE THREAD

**Issue by bpdesigns** [18F/ux-guide#378]
### A Description of work
Tactical information about how to get PRA approval and the fast track process is not mentioned in the ux guide. PRA is mentioned several times in the guide but it could be more helpful.

**references for review**
- https://pra.digital.gov/
- slide 35-36 of this slide [deck](https://docs.google.com/presentation/d/15UVLBnmlsKnFBQmjAVWRe9HntSDCsq12ZTjlKovVS98/edit#slide=id.g20c56d5d7ab_5_38)
- 2022 PRA review [doc](https://docs.google.com/document/d/1r0-AQ6DChw3FoZEV9q6K9dnhEa05uwLyPcEzLAV74FI/edit)
- notes and recording from this [research guild session](https://docs.google.com/document/d/1QFreBLN_AwDJi5ooIwO3xFGADMat5G8hyAw1drCjyTw/edit)

### Point of contact on this issue
You can reach out to @bpdesigns 

**Billable?**

- [ ] Yes
- [x] No
If yes, tock code:

**Skills needed**

- [x] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [x] No

How much time do you anticipate this work taking?
-  under two weeks

### Tasks 
- [x] review references (above)
- [x] create a doc with updated content
- [x] share doc with @bpdesigns and the #g-research slack channel for review
- [ ] implement approved changes. 

### Acceptance criteria
- [ ] Updated PRA guidance is added to the Plan and Legal pages of the UX Guide.

**Comment by melchoyce** [comment]
I believe @amandacostello has a PRA presentation as well we might be able to borrow from?

**Comment by amandacostello** [comment]
I absolutely do! [My PRA preso, complete with fluffy cows.](https://docs.google.com/presentation/d/10UsYgE_GMLjUdvCeLCTlsMzjgpGgwvu6sUQECRcMUjs/edit#slide=id.gf6a1755d6b_0_5)

**Comment by egamble23** [comment]
Hi @bpdesigns , I've been working on this issue. @amandacostello has kindly share some links to Methods that also mention PRA:
https://methods.18f.gov/fundamentals/recruiting/
https://methods.18f.gov/discover/contextual-inquiry/

For the scope of this issue, should I be considering those above and any other pages in other spaces, as well as the UX guide?  Just wish to understand better as I'm getting familiar with the content. Thanks!

**Comment by bpdesigns** [comment]
@egamble23 the scope of this issue is updating content in the ux guide. I think once this issue is complete it would make sense to create a new TLC ticket link to the new ux guide content from the methods site links you shared above. I'm happy to have a call to talk though anything else that would be helpful to clarify.

**Comment by egamble23** [comment]
Many thanks, @bpdesigns ! Appreciate the clarifications on the scope. I'll follow up.

**Comment by egamble23** [comment]
I don't have access to edit the ticket to mark progress on this ticket so am updating this comment thread with a checklist for tracking progress made:

- [ ] Desk research. Sourced references include Amanda Costello, Megan Moser, Becky Slogeris, PRA website. 
- [ ] Review of current relevant content [[messy notes doc](https://docs.google.com/document/d/1eXPs5QfpFfdAdAQdyTlRzrwmV-3KFYmBptltNXu7JI4/edit?usp=sharing)]
- [ ] Scope clarified
- [ ] Draft outline check-in – check with ticket author on direction of approaches
- [ ] Proposals to Ben on possible cross links 
- [ ] Content reviews by Subject Matter Experts (Amanda Costello, Megan Moser, PRA contacts for coordination/awareness/sensitivities – Erin to ask Amanda)
- [ ] Refinements based on feedback
- [ ] Coordination with Matt Dobson for awareness re: PRA
- [ ] Review by ticket author (Ben)
- [ ] Final refinements
- [ ] Add to UX Guide

**Comment by MelissaBraxton** [comment]
@egamble23  - FYI: I added you to the GitHub Team so you now can edit issues like this (the checklist in the comment is fine though--no need to do anything else to track your progress here!). Sorry you didn't get access sooner!

**Comment by egamble23** [comment]
Thanks so much, @MelissaBraxton ! Much appreciated! Sounds good.

**Comment by egamble23** [comment]
Hi @bpdesigns , as you saw on Slack, on May 10 I shared the [draft subsection text](https://docs.google.com/document/d/1P6cAd1sEt7ZcCUEyQcIpdz1hNzc1MaJfkXriMY_i6qY/edit) in the g-research Slack Channel. 

I'm going to clean it up and share again as a clean Google doc with Nicole Bynum, Robert Jolly, Matt Dobson, and Amanda Costello, as an fyi as to the cleaned up version for any final comments.

I can then start working on a pull request in GitHub. In addition to you as the issue author, who would be good to add on as a reviewer(s)? Happy to add whoever would be good as final reviewer. 

Many thanks for your guidance!
Erin

**Comment by bpdesigns** [comment]
Thanks @egamble23 the list of folks already reviewing is great. No need for another additional reviewer.

**Comment by bpdesigns** [comment]
Thanks @egamble23! Looks great :)
