### ISSUE TITLE
Define research to understand how DEIA informs our work 

### ISSUE THREAD

**Issue by bpdesigns** [18F/ux-guide#379]
**Background**
The 18F team has evolved our design research practices and deepened our work addressing DEIA. Its time to reflect as a group how we practice now and what standards we want to hold ourselves to as we work to deliver more equitably for the public.

**Acceptance criteria (we'll know we're done when...)**
- [ ] we have a research plan for how  to review and define our updated practices 

**Tasks**
- [ ] Decide when, where, how to review and define our updated practices
- [ ] Create a research plan and facilitation script to learn from other 18F designers about their current practices

Definition of done
- [ ]  One of the POs has approved the reviewed the research plan
