### ISSUE TITLE
Publish about article

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/ux-guide#38]
**Background**
We have approval from the design chapter and team to publish this article. 

**Acceptance criteria** 
- [ ] Outreach has reviewed and approved content
- [ ] Article is publicly available 

**Tasks**
- [x] Create writing lab issue for this article
- [x] Have outreach review and approve Google doc
- [x] Have Angela review and approve Google doc. 
- [X] Update GitHub to reflect approved content in Google doc
- [ ] Identify opportunities to link with Method Cards
- [ ] Make the content public
- [ ] Announce the publication in Slack

**Definition of done**
- [ ]  One of the POs has approved the change
- [X]  Outreach approval (if needed)
