### ISSUE TITLE
Review the DEIA Growth for Teams report and Action guide for content to add to Methods and UX Guide

### ISSUE THREAD

**Issue by bpdesigns** [18F/ux-guide#380]
**Background**
The DEIA Growth for Teams project conducted foundational research into how we could improve our practices to account for DEIA. The insights or ideas from that team have not been piloted or incorporated into our regular practices. 

**Acceptance criteria _(we'll know we're done when…)_** 
- [x] The DEIA Growth for Teams report and Action guide have been reviewed 
- [x] New issues for implementing new content have been added to the 18F UX Guide and Methods Shared Project board

**Tasks**
- [x] Review the DEIA Growth for Teams report and Action guide for content to add to Methods and UX Guide
- [x] Identify potential new methods and practices 18F could adopt
- [x] Create new issues for implementing new content in the 18F UX Guide and Methods Shared Project board
- [x]  PO review

**Comment by bpdesigns** [comment]
potential text to [include](https://docs.google.com/document/d/1WxH5DnJvkQstXkQb54wlqaAtr44GAC2fJejuBdlPix4/edit#)

**Comment by bpdesigns** [comment]
The relevant content from the Growth for teams report was added as edits to the greater service design update to the guide. 

I also created a draft pull request to update the Ethics page #395

**Comment by christophermather** [comment]
Marked as done on 4/17/2023. Marking as "Closed" now
