### ISSUE TITLE
Draft new content for the UX Guide "design" section on diagramming/modeling

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/ux-guide#388]
Before you submit your new issue, add labels so that we know which guide/site the work is relevant to. E.g., if the work needs to be done on both the UX guide and the methods cards sites, then add the "UX guide" and the "method cards" labels. Once you're done, delete the text above the line. :)

While it might seem redundant, we have one team that manages issues across multiple products, and these labels help us keep our wires straight! 
_______________________________________________________

### Point of contact on this issue
@bpdesigns or @MelissaBraxton 

______________________________________

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

**How much time do you anticipate this work taking?**
1-2 weeks

**Background**
The UX Guide is heavily skewed toward research and does not cover diagramming and modeling design approaches that are very common at 18F. This issue covers drafting content to describe how we create diagrams, maps, and models to help us identify and understand problems, make sense of complexity, and explore solution ideas.

This issue could be broken up into smaller chunks if need be. One example of how it could be broken up: 
 - Make an outline
 - 1st draft
 - shepherd content through review/approval processes
 - Address requested revisions and comments
 - Implement content in code

The work could also be broken up by different diagramming approaches (system map, task flow, service blueprint, mental model, etc.)

**Acceptance criteria _(we'll know we're done when…)_** 
- [ ] Content that describes how 18F designers use diagramming, mapping, modeling in their design practice is live in the UX guide

**Tasks**
- [ ]  Make an outline
- [ ]  Write content
- [ ]  PO review [if task involves content changes] 
- [ ] Refine comment based on feedback
- [ ] Implement content
- [ ]  Accessibility review [if needed]
- [ ]  Outreach approval [if needed]

**Comment by MelissaBraxton** [comment]
@bpdesigns  - The SD working group was hoping we could shape up this issue to be picked up or at least started by the DA team. Take a look and let me know what you think!

**Comment by bpdesigns** [comment]
Seems good to me.

**Comment by lauranash18f** [comment]
We have slides/recording/transcripts from Abby Covert's How to Diagram training last year, which should help the future author! https://drive.google.com/drive/folders/1Kww85gsre2Fi_9EKNBJKw99tvzQ4vmZj?usp=share_link
