### ISSUE TITLE
Publish resources article

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/ux-guide#39]
**Background**
We have approval from the design chapter and team to publish this article. 

**Acceptance criteria** 
- [x] Outreach has reviewed and approved content
- [ ] Article is publicly available 

**Tasks**
- [x] Create writing lab issue for this article
- [x] Have outreach review and approve Google doc
- [ ] Have Angela review and approve Google doc. 
- [ ] Identify opportunities to link with Method Cards
- [ ] Update GitHub to reflect approved content in Google doc
- [ ] Make the content public
- [ ] Announce the publication in Slack

**Definition of done**
- [ ]  One of the POs has approved the change
- [ ]  Outreach approval (if needed)

**Comment by MelissaBraxton** [comment]
Moving this to blocked until after we can get privacy office approval for participant agreement template

**Comment by MelissaBraxton** [comment]
Privacy Officer approved the participant agreement form on 7/25/19.
