### ISSUE TITLE
htmlproofer build process fails for non-existent link

### ISSUE THREAD

**Issue by geekygirlsarah** [18F/ux-guide#394]
**Point of contact**

Delivery Assurance team, though @geekygirlsarah is happy to show the problem

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

**How much time do you anticipate this work taking?**

About a day

**Background**

The htmlproofer action checks every link on the site to make sure it exists and doesn't return a 404 error. When it spins up the site locally, it runs through the links. It finds the Participant Agreement in Spanish to be an invalid link despite both the page itself and the link that points to it exist and seem correct. But this shows up as an error for every PR now.

This appears to have happened after commits c969788c6b4a43509aded18d401531064cbefc7c and f833bc5cab01ef940e6cd301e9bd8fa09997b6a8 which renames the page and updates the agreement. (They were committed to `main` directly and therefore didn't have the proofer review it first.)

**Acceptance criteria _(we'll know we're done when…)_** 
- [ ] Upon making the PR for this issue, all the checks/actions will pass

**Tasks**
- [ ] Find the correct filename and/or link that need to get changed. (see `_pages/resources/participant-agreement.md` and `particpant-agreement-spanish.md`)
- [ ]  PO review [if task involves content changes] 
- [ ]  Accessibility review [if needed]
- [ ]  Outreach approval [if needed]
