### ISSUE TITLE
Update guidance on Trauma informed research practices Part 2

### ISSUE THREAD

**Issue by bpdesigns** [18F/ux-guide#396]
**Background**
This is a follow on ticket from #291 

There is no guidance on Trauma informed research practices in the ux guide but should be. 

**reference material**

Potentially we could update the following pages: 
- [ethical considerations](https://ux-guide.18f.gov/research/plan/#ethical-considerations)
- [Preparing an interview guide](https://ux-guide.18f.gov/research/do/#preparing-an-interview-guide)
- [getting informed consent](https://ux-guide.18f.gov/research/do/#getting-informed-consent)
- [moderating research sessions](https://ux-guide.18f.gov/research/do/#moderating-research-sessions)
- [ethics](https://ux-guide.18f.gov/research/ethics/) 

**Acceptance criteria** 
- [ ] guidance on trauma informed research is updated in the UX Guide. 

**Tasks**
- [ ] review new content approved from [Part 1 of this ticket](https://github.com/18F/ux-guide/issues/291)  
- [ ] determine where new content should be added to the UX Guide (see references above for ideas)
- [ ] update the doc or create pull requests for where the content should be updated 
- [ ] review from @bpdesigns or @MelissaBraxton 
- [ ] update content in github

### Point of contact on this issue
You can reach out to @bpdesigns 

**Billable?**

- [ ] Yes
- [x] No
If yes, tock code:

**Skills needed**

- [x] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [x] No

How much time do you anticipate this work taking?
-  1-2 weeks
- 
**Definition of done**
- [ ]  @bpdesigns has approved the update

**Comment by bpdesigns** [comment]
addressed in Part -1
