### ISSUE TITLE
Implement 371

### ISSUE THREAD

**Issue by bpdesigns** [18F/ux-guide#397]
**Background**
The 18F service design practice area needs to document our practices. [#371 ](https://github.com/18F/ux-guide/issues/371)focused on creating that content. This ticket is to implement these changes. 

**Acceptance criteria _(we'll know we're done when…)_** 
- [ ] We have content in the UX Guide that accurately reflects 18F's service design practice.

**Tasks**
- [x] Create a pull request in the UX guide to make the edits laid out in [this doc](https://docs.google.com/document/d/1wNBZoftlRvJbLK-5uazsQOG_2HpPMyLjmAHSGLOCBpU/edit#)
- [x] Tag @bpdesigns and @elisaachen as reviewers

**Reviewers**
- [ ] @bpdesigns

**Comment by bpdesigns** [comment]
@MelissaBraxton for your awareness.

**Comment by MelissaBraxton** [comment]
Here's the link to the doc w/ new content and changes: https://docs.google.com/document/d/1wNBZoftlRvJbLK-5uazsQOG_2HpPMyLjmAHSGLOCBpU/edit#

**Comment by alexbielen** [comment]
From increment planning: 

Concern: 85 pages of content in Google Docs. Need to thoroughly go through each page and make updates. Not feeling like a big risk or concern. Just might take awhile. (Perhaps a candidate to break into pages?)

**Comment by evoeges** [comment]
Made a new branch called [service-design-updates](https://github.com/18F/ux-guide/tree/service-design-updates) and will push changes by section (eg: just pushed updates to about.md to the new branch).

**Comment by evoeges** [comment]
@bpdesigns or @elisaachen when you have a minute can you take a look at the new branch I made and the PRs and just give me a thumbsup if I'm doing this right? Haven't contributed to any of the guides on github yet so just want to be sure!

**Comment by bpdesigns** [comment]
@evoeges looks good to me!

**Comment by evoeges** [comment]
All edits to date have been made! There were a couple of comments I left in [the doc ](https://docs.google.com/document/d/1wNBZoftlRvJbLK-5uazsQOG_2HpPMyLjmAHSGLOCBpU/edit#) that need to be addressed: one small section appeared incomplete, and there were a few places with missing links.

I also noticed that there are some sections of the UX guide not in the doc, so they have no edits.

**Comment by evoeges** [comment]
@bpdesigns and @elisaachen I'll close this ticket pending your review.

**Comment by bpdesigns** [comment]
@evoeges I made one comment in the doc where I think a word is missing, otherwise this looks great. Well done! That was a lot of work :)

**Comment by evoeges** [comment]
I addressed your comment @bpdesigns and pushed the change. I think this ticket is ready to close out and any new changes can be new tickets!
