### ISSUE TITLE
Develop plan for publishing articles on a rolling basis

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/ux-guide#41]
**Background**
We need a plan for where and how to publish articles one at a time. 

**Acceptance criteria** 
- [ ] We have a publication plan and it's findable on GitHub

**Tasks**
- [ ] Draft plan
- [ ] Run it by outreach
- [ ] Publish on GitHub

**Definition of done**
- [ ]  One of the POs has approved the change
- [ ]  Outreach approval (if needed)
