### ISSUE TITLE
Publish Part 1 of the guide

### ISSUE THREAD

**Issue by NorahMaki** [18F/ux-guide#63]
Pending review from Outreach and Director

**Comment by MelissaBraxton** [comment]
**Background**
We have approval from the design chapter and team to publish this article. 

**Acceptance criteria** 
- [X] Outreach has reviewed and approved content
- [ ] Article is publicly available 

**Tasks**
- [x] Create writing lab issue for this article
- [x] Have outreach review and approve Google doc
- [x] Have Angela review and approve Google doc. 
- [ ] Update GitHub to reflect approved content in Google doc
- [ ] Identify opportunities to link with Method Cards
- [ ] Announce the publication in Slack

**Definition of done**
- [ ]  One of the POs has approved the change
- [X]  Outreach approval (if needed)

**Comment by MelissaBraxton** [comment]
Closing as we will publish and announce all sections of the guide at the same time.
